import { createIntegrationRegistry } from "@mistle/integrations-definitions/server";
import { describe, expect, it } from "vitest";

import { SyncIntegrationTargetsForTests } from "./sync-integration-targets.js";

describe("sync-integration-targets", () => {
  it("builds target sync entries from the registry with disabled defaults", () => {
    const integrationRegistry = createIntegrationRegistry();
    const targets = SyncIntegrationTargetsForTests.buildSyncIntegrationTargets(integrationRegistry);

    expect(targets).toEqual([
      {
        targetKey: "agentmail-mcp",
        familyId: "agentmail",
        variantId: "agentmail-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "anthropic-default",
        familyId: "anthropic",
        variantId: "anthropic-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "autumn-mcp",
        familyId: "autumn",
        variantId: "autumn-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "aws-cli-default",
        familyId: "aws",
        variantId: "aws-cli-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "bugsnag-mcp",
        familyId: "bugsnag",
        variantId: "bugsnag-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "cloudflare-mcp",
        familyId: "cloudflare",
        variantId: "cloudflare-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "datadog-default",
        familyId: "datadog",
        variantId: "datadog-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "deepseek-default",
        familyId: "deepseek",
        variantId: "deepseek-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "e2b-default",
        familyId: "e2b",
        variantId: "e2b-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "expo-mcp",
        familyId: "expo",
        variantId: "expo-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "fireworks-default",
        familyId: "fireworks",
        variantId: "fireworks-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "gcp-mcp",
        familyId: "gcp",
        variantId: "gcp-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "github-cloud",
        familyId: "github",
        variantId: "github-cloud",
        enabled: false,
        config: {},
      },
      {
        targetKey: "github-enterprise-server",
        familyId: "github",
        variantId: "github-enterprise-server",
        enabled: false,
        config: {},
      },
      {
        targetKey: "google-analytics-mcp",
        familyId: "google-analytics",
        variantId: "google-analytics-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "google-workspace-mcp",
        familyId: "google-workspace",
        variantId: "google-workspace-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "inception-default",
        familyId: "inception",
        variantId: "inception-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "jira-default",
        familyId: "jira",
        variantId: "jira-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "kimi-default",
        familyId: "kimi",
        variantId: "kimi-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "klaviyo-mcp",
        familyId: "klaviyo",
        variantId: "klaviyo-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "linear-default",
        familyId: "linear",
        variantId: "linear-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "metaads-default",
        familyId: "metaads",
        variantId: "metaads-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "minimax-default",
        familyId: "minimax",
        variantId: "minimax-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "modal-default",
        familyId: "modal",
        variantId: "modal-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "notion-mcp",
        familyId: "notion",
        variantId: "notion-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "openai-default",
        familyId: "openai",
        variantId: "openai-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "opencode-go",
        familyId: "opencode",
        variantId: "opencode-go",
        enabled: false,
        config: {},
      },
      {
        targetKey: "opencomputer-default",
        familyId: "opencomputer",
        variantId: "opencomputer-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "openrouter-default",
        familyId: "openrouter",
        variantId: "openrouter-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "planetscale-mcp",
        familyId: "planetscale",
        variantId: "planetscale-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "posthog-mcp",
        familyId: "posthog",
        variantId: "posthog-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "railway-mcp",
        familyId: "railway",
        variantId: "railway-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "render-mcp",
        familyId: "render",
        variantId: "render-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "resend-mcp",
        familyId: "resend",
        variantId: "resend-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "sentry-mcp",
        familyId: "sentry",
        variantId: "sentry-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "shopify-default",
        familyId: "shopify",
        variantId: "shopify-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "signoz-mcp",
        familyId: "signoz",
        variantId: "signoz-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "slack-default",
        familyId: "slack",
        variantId: "slack-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "stripe-mcp",
        familyId: "stripe",
        variantId: "stripe-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "supabase-mcp",
        familyId: "supabase",
        variantId: "supabase-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "tensorlake-default",
        familyId: "tensorlake",
        variantId: "tensorlake-default",
        enabled: false,
        config: {},
      },
      {
        targetKey: "wasenderapi-mcp",
        familyId: "wasenderapi",
        variantId: "wasenderapi-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "whapi-mcp",
        familyId: "whapi",
        variantId: "whapi-mcp",
        enabled: false,
        config: {},
      },
      {
        targetKey: "zai-coding-plan",
        familyId: "zai",
        variantId: "zai-coding-plan",
        enabled: false,
        config: {},
      },
    ]);
  });
});
