import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseToml, stringify as stringifyToml } from "smol-toml";

import type { ConfigRecord } from "./presets/development/types.ts";

import { developmentPresetModules } from "./presets/development/index.ts";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..", "..");
const SAMPLE_PATH = join(REPO_ROOT, "config", "config.sample.toml");
const TARGET_PATH = join(REPO_ROOT, "config", "config.development.toml");
const GENERATED_HEADER = [
  "# Generated by `pnpm config:init:dev`.",
  "# Edit this file as needed for your local environment.",
  "",
].join("\n");

function isRecord(value: unknown): value is ConfigRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function asRecord(value: unknown): ConfigRecord {
  if (!isRecord(value)) {
    return {};
  }

  return value;
}

function deepClone(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((item) => deepClone(item));
  }

  if (isRecord(value)) {
    const clonedEntries: [string, unknown][] = [];

    for (const [key, entryValue] of Object.entries(value)) {
      clonedEntries.push([key, deepClone(entryValue)]);
    }

    return Object.fromEntries(clonedEntries);
  }

  return value;
}

function mergeRecords(base: ConfigRecord, override: ConfigRecord): ConfigRecord {
  const merged: ConfigRecord = { ...base };

  for (const [key, overrideValue] of Object.entries(override)) {
    const baseValue = merged[key];

    if (isRecord(baseValue) && isRecord(overrideValue)) {
      merged[key] = mergeRecords(baseValue, overrideValue);
      continue;
    }

    merged[key] = deepClone(overrideValue);
  }

  return merged;
}

function buildDevelopmentDefaults(): ConfigRecord {
  let defaults: ConfigRecord = {};

  for (const presetModule of developmentPresetModules) {
    defaults = mergeRecords(defaults, asRecord(presetModule.defaults));
  }

  return defaults;
}

function getValueAtPath(root: ConfigRecord, path: readonly string[]): unknown {
  let current: unknown = root;

  for (const segment of path) {
    if (!isRecord(current)) {
      return undefined;
    }

    current = current[segment];
  }

  return current;
}

function setValueAtPath(root: ConfigRecord, path: readonly string[], value: unknown): ConfigRecord {
  if (path.length === 0) {
    return root;
  }

  const nextRoot: ConfigRecord = { ...root };
  let cursor: ConfigRecord = nextRoot;

  for (let index = 0; index < path.length - 1; index += 1) {
    const segment = path[index];
    if (segment === undefined) {
      throw new Error("Generator path contained an undefined segment.");
    }

    const existing = cursor[segment];
    const nextSegment: ConfigRecord = isRecord(existing) ? { ...existing } : {};
    cursor[segment] = nextSegment;
    cursor = nextSegment;
  }

  const finalSegment = path[path.length - 1];
  if (finalSegment === undefined) {
    throw new Error("Generator path contained an undefined segment.");
  }

  cursor[finalSegment] = value;
  return nextRoot;
}

function applyDevelopmentGenerators(configRoot: ConfigRecord): ConfigRecord {
  let nextRoot: ConfigRecord = configRoot;

  for (const presetModule of developmentPresetModules) {
    const generators = presetModule.generators ?? [];

    for (const generator of generators) {
      if (generator.path.length === 0) {
        throw new Error("Generator path must be a non-empty array.");
      }

      const currentValue = getValueAtPath(nextRoot, generator.path);
      const when = generator.when ?? "missing";

      if (when === "missing" && currentValue !== undefined) {
        continue;
      }

      const generatedValue = generator.generate({
        config: nextRoot,
        currentValue,
      });

      nextRoot = setValueAtPath(nextRoot, generator.path, generatedValue);
    }
  }

  return nextRoot;
}

function main(): void {
  if (process.argv.length > 2) {
    throw new Error("This script does not accept arguments.");
  }

  if (!existsSync(SAMPLE_PATH)) {
    throw new Error(`Missing sample config file at: ${SAMPLE_PATH}`);
  }

  if (existsSync(TARGET_PATH)) {
    console.log(`Config already exists: ${TARGET_PATH}`);
    return;
  }

  const sampleContent = readFileSync(SAMPLE_PATH, "utf8");
  const sampleConfigRoot = asRecord(parseToml(sampleContent));

  const defaults = buildDevelopmentDefaults();
  const withDefaults = mergeRecords(sampleConfigRoot, defaults);
  const withGeneratedValues = applyDevelopmentGenerators(withDefaults);

  const developmentContent = `${GENERATED_HEADER}${stringifyToml(withGeneratedValues)}`;

  mkdirSync(dirname(TARGET_PATH), { recursive: true });
  writeFileSync(TARGET_PATH, developmentContent, "utf8");

  console.log(`Initialized development config: ${TARGET_PATH}`);
}

try {
  main();
} catch (error) {
  if (error instanceof Error) {
    console.error(error.message);
  } else {
    console.error(String(error));
  }
  process.exitCode = 1;
}
