import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { loadConfig } from "../../packages/config/src/loader.ts";
import { AppIds } from "../../packages/config/src/modules.ts";
import { buildDevelopmentTomlConfig, stringifyTomlConfig } from "./toml-config.ts";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..", "..");
const TARGET_PATH = join(REPO_ROOT, "config", "config.development.toml");
const GENERATED_HEADER = [
  "# Generated by `pnpm config:init:dev`.",
  "# Uses the resource-oriented TOML shape.",
  "# Edit this file as needed for your local environment.",
  "",
].join("\n");

function validateWrittenDevelopmentConfig(configPath: string): void {
  loadConfig({ app: AppIds.CONTROL_PLANE_API, configPath });
  loadConfig({ app: AppIds.CONTROL_PLANE_WORKER, configPath });
  loadConfig({ app: AppIds.DATA_PLANE_API, configPath });
  loadConfig({ app: AppIds.DATA_PLANE_GATEWAY, configPath });
  loadConfig({ app: AppIds.DATA_PLANE_WORKER, configPath });
  loadConfig({ app: AppIds.TOKENIZER_PROXY, configPath });
}

function main(): void {
  if (process.argv.length > 2) {
    throw new Error("This script does not accept arguments.");
  }

  const developmentContent = stringifyTomlConfig({
    header: GENERATED_HEADER,
    configRoot: buildDevelopmentTomlConfig(),
  });

  mkdirSync(dirname(TARGET_PATH), { recursive: true });
  writeFileSync(TARGET_PATH, developmentContent, "utf8");
  validateWrittenDevelopmentConfig(TARGET_PATH);

  console.log(`Initialized development config: ${TARGET_PATH}`);
}

try {
  main();
} catch (error) {
  if (error instanceof Error) {
    console.error(error.message);
  } else {
    console.error(String(error));
  }
  process.exitCode = 1;
}
