import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { loadConfig } from "../../packages/config/src/loader.ts";
import { AppIds } from "../../packages/config/src/modules.ts";
import {
  getRequiredIntegrationConfigValues,
  getIntegrationProviderPreset,
  IntegrationConfigFileNames,
  IntegrationSandboxProvider,
  parseIntegrationSandboxProviders,
} from "./presets/integration/index.ts";
import {
  applyTomlConfigEnvOverrides,
  buildIntegrationTomlConfig,
  getValueAtTomlConfigPath,
  isMissingRequiredConfigValue,
  stringifyTomlConfig,
  type ConfigRecord,
} from "./toml-config.ts";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..", "..");

function buildGeneratedHeader(providers: readonly IntegrationSandboxProvider[]): string {
  return [
    "# Generated by `pnpm config:init:integration`.",
    "# Uses the resource-oriented TOML shape.",
    `# Enabled sandbox provider config: ${providers.join(", ")}.`,
    "",
  ].join("\n");
}

function assertRequiredConfigValues(input: {
  providers: readonly IntegrationSandboxProvider[];
  configRoot: ConfigRecord;
}): void {
  for (const requiredValue of getRequiredIntegrationConfigValues(input)) {
    const value = getValueAtTomlConfigPath(input.configRoot, requiredValue.path);
    if (isMissingRequiredConfigValue(value)) {
      throw new Error(
        `Missing required config value at ${requiredValue.path.join(".")} for enabled providers "${input.providers.join(",")}". Set ${requiredValue.envVar} before running \`pnpm config:init:integration\`.`,
      );
    }
  }
}

async function buildIntegrationConfig(input: {
  providers: readonly IntegrationSandboxProvider[];
  env: NodeJS.ProcessEnv;
}): Promise<ConfigRecord> {
  const remoteSandboxProvider = input.providers.find(
    (provider) =>
      provider === IntegrationSandboxProvider.E2B ||
      provider === IntegrationSandboxProvider.TENSORLAKE,
  );
  const remotePreset =
    remoteSandboxProvider === undefined
      ? undefined
      : await getIntegrationProviderPreset(remoteSandboxProvider);
  const remoteSandboxBaseImage = remotePreset?.remoteSandboxBaseImage;
  const configRootInput = {
    providers: input.providers,
    environment: input.env,
    ...(remoteSandboxBaseImage === undefined ? {} : { remoteSandboxBaseImage }),
  };
  const configRoot = buildIntegrationTomlConfig(configRootInput);
  const withEnvOverrides = applyTomlConfigEnvOverrides({
    configRoot,
    environment: input.env,
  });

  assertRequiredConfigValues({
    providers: input.providers,
    configRoot: withEnvOverrides,
  });

  return withEnvOverrides;
}

async function writeIntegrationConfig(input: {
  providers: readonly IntegrationSandboxProvider[];
  configRoot: ConfigRecord;
}): Promise<string> {
  const targetPath = join(REPO_ROOT, "config", IntegrationConfigFileNames.DEFAULT);
  const content = stringifyTomlConfig({
    header: buildGeneratedHeader(input.providers),
    configRoot: input.configRoot,
  });

  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, content, "utf8");
  return targetPath;
}

function validateWrittenIntegrationConfig(configPath: string): void {
  loadConfig({ app: AppIds.CONTROL_PLANE_API, configPath });
  loadConfig({ app: AppIds.CONTROL_PLANE_WORKER, configPath });
  loadConfig({ app: AppIds.DATA_PLANE_API, configPath });
  loadConfig({ app: AppIds.DATA_PLANE_GATEWAY, configPath });
  loadConfig({ app: AppIds.DATA_PLANE_WORKER, configPath });
}

async function generateIntegrationConfigFiles(input: {
  providers: readonly IntegrationSandboxProvider[];
  env: NodeJS.ProcessEnv;
}): Promise<void> {
  const configRoot = await buildIntegrationConfig({
    providers: input.providers,
    env: input.env,
  });
  const configPath = await writeIntegrationConfig({
    providers: input.providers,
    configRoot,
  });
  validateWrittenIntegrationConfig(configPath);
  console.log(`Initialized integration config (${input.providers.join(",")}): ${configPath}`);
}

async function main(): Promise<void> {
  if (process.argv.length > 2) {
    throw new Error("This script does not accept arguments.");
  }

  const providers = parseIntegrationSandboxProviders(
    process.env.MISTLE_TEST_SANDBOX_INTEGRATION_PROVIDERS,
  );

  await generateIntegrationConfigFiles({ providers, env: process.env });
}

void main().catch((error: unknown) => {
  if (error instanceof Error) {
    console.error(error.message);
  } else {
    console.error(String(error));
  }

  process.exitCode = 1;
});
