import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parse as parseToml, stringify as stringifyToml } from "smol-toml";

import { convertEnvToTomlRecord } from "../../packages/config/src/conversion.ts";
import { mergeConfigRoots } from "../../packages/config/src/core/merge.ts";
import {
  asObjectRecord,
  getValueAtPath,
  isObjectRecord,
  setValueAtPath,
} from "../../packages/config/src/core/record.ts";
import { loadConfig } from "../../packages/config/src/loader.ts";
import { AppIds } from "../../packages/config/src/modules.ts";
import { developmentPresetModules } from "./presets/development/index.ts";
import type { ConfigRecord, DevelopmentPresetModule } from "./presets/development/types.ts";
import {
  getIntegrationProviderPreset,
  parseIntegrationSandboxProviders,
  type IntegrationSandboxProvider,
} from "./presets/integration/index.ts";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..", "..");
const SAMPLE_PATH = join(REPO_ROOT, "config", "config.sample.toml");

function buildGeneratedHeader(provider: IntegrationSandboxProvider): string {
  return [
    "# Generated by `pnpm config:init:integration`.",
    `# Sandbox provider: ${provider}.`,
    "",
  ].join("\n");
}

function buildPresetDefaults(modules: readonly DevelopmentPresetModule[]): ConfigRecord {
  let defaults: ConfigRecord = {};

  for (const presetModule of modules) {
    defaults = mergeConfigRoots(defaults, presetModule.defaults ?? {});
  }

  return defaults;
}

function applyPresetGenerators(
  configRoot: ConfigRecord,
  modules: readonly DevelopmentPresetModule[],
): ConfigRecord {
  let nextRoot: ConfigRecord = configRoot;

  for (const presetModule of modules) {
    const generators = presetModule.generators ?? [];

    for (const generator of generators) {
      if (generator.path.length === 0) {
        throw new Error("Generator path must be a non-empty array.");
      }

      const currentValue = getValueAtPath(nextRoot, generator.path);
      const when = generator.when ?? "missing";

      if (when === "missing" && currentValue !== undefined) {
        continue;
      }

      const generatedValue = generator.generate({
        config: nextRoot,
        currentValue,
      });

      nextRoot = setValueAtPath(nextRoot, generator.path, generatedValue);
    }
  }

  return nextRoot;
}

function deleteValueAtPath(
  root: Record<string, unknown>,
  path: readonly string[],
): Record<string, unknown> {
  if (path.length === 0) {
    return root;
  }

  const [head, ...tail] = path;
  if (head === undefined) {
    throw new Error("Deletion path contained an undefined segment.");
  }

  const nextRoot: Record<string, unknown> = { ...root };

  if (tail.length === 0) {
    delete nextRoot[head];
    return nextRoot;
  }

  const childValue = nextRoot[head];
  if (!isObjectRecord(childValue)) {
    return nextRoot;
  }

  const nextChild = deleteValueAtPath(childValue, tail);
  if (Object.keys(nextChild).length === 0) {
    delete nextRoot[head];
    return nextRoot;
  }

  nextRoot[head] = nextChild;
  return nextRoot;
}

function assertRequiredConfigValues(input: {
  provider: IntegrationSandboxProvider;
  configRoot: Record<string, unknown>;
}): void {
  const preset = getIntegrationProviderPreset(input.provider);

  for (const requiredValue of preset.requiredConfigValues) {
    const value = getValueAtPath(input.configRoot, requiredValue.path);
    if (
      typeof value !== "string" ||
      value.trim().length === 0 ||
      value.startsWith("replace-with-")
    ) {
      throw new Error(
        `Missing required config value at ${requiredValue.path.join(".")} for provider "${input.provider}". Set ${requiredValue.envVar} before running \`pnpm config:init:integration\`.`,
      );
    }
  }
}

function buildDevelopmentBaseConfig(
  sampleConfigRoot: Record<string, unknown>,
): Record<string, unknown> {
  const defaults = buildPresetDefaults(developmentPresetModules);
  const withDefaults = mergeConfigRoots(sampleConfigRoot, defaults);
  return applyPresetGenerators(withDefaults, developmentPresetModules);
}

function buildIntegrationConfig(input: {
  provider: IntegrationSandboxProvider;
  sampleConfigRoot: Record<string, unknown>;
  env: NodeJS.ProcessEnv;
}): Record<string, unknown> {
  const preset = getIntegrationProviderPreset(input.provider);
  const developmentBaseConfig = buildDevelopmentBaseConfig(input.sampleConfigRoot);
  const withProviderDefaults = mergeConfigRoots(developmentBaseConfig, preset.defaults);
  const withEnvOverrides = mergeConfigRoots(
    withProviderDefaults,
    convertEnvToTomlRecord(input.env),
  );

  let nextConfig = setValueAtPath(
    withEnvOverrides,
    ["global", "sandbox", "provider"],
    input.provider,
  );

  for (const prunePath of preset.prunePaths) {
    nextConfig = deleteValueAtPath(nextConfig, prunePath);
  }

  assertRequiredConfigValues({
    provider: input.provider,
    configRoot: nextConfig,
  });

  return nextConfig;
}

function writeIntegrationConfig(input: {
  provider: IntegrationSandboxProvider;
  configRoot: Record<string, unknown>;
}): string {
  const preset = getIntegrationProviderPreset(input.provider);
  const targetPath = join(REPO_ROOT, "config", preset.outputFileName);
  const content = `${buildGeneratedHeader(input.provider)}${stringifyToml(input.configRoot)}`;

  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, content, "utf8");
  return targetPath;
}

function validateWrittenIntegrationConfig(configPath: string): void {
  loadConfig({ app: AppIds.CONTROL_PLANE_API, configPath });
  loadConfig({ app: AppIds.CONTROL_PLANE_WORKER, configPath });
  loadConfig({ app: AppIds.DATA_PLANE_API, configPath });
  loadConfig({ app: AppIds.DATA_PLANE_GATEWAY, configPath });
  loadConfig({ app: AppIds.DATA_PLANE_WORKER, configPath });
  loadConfig({ app: AppIds.TOKENIZER_PROXY, configPath });
}

function generateIntegrationConfigFiles(input: {
  providers: readonly IntegrationSandboxProvider[];
  sampleConfigRoot: Record<string, unknown>;
  env: NodeJS.ProcessEnv;
}): void {
  for (const provider of input.providers) {
    const configRoot = buildIntegrationConfig({
      provider,
      sampleConfigRoot: input.sampleConfigRoot,
      env: input.env,
    });
    const configPath = writeIntegrationConfig({
      provider,
      configRoot,
    });
    validateWrittenIntegrationConfig(configPath);
    console.log(`Initialized integration config (${provider}): ${configPath}`);
  }
}

function main(): void {
  if (process.argv.length > 2) {
    throw new Error("This script does not accept arguments.");
  }

  if (!existsSync(SAMPLE_PATH)) {
    throw new Error(`Missing sample config file at: ${SAMPLE_PATH}`);
  }

  const rawSampleContent = readFileSync(SAMPLE_PATH, "utf8");
  const sampleConfigRoot = asObjectRecord(parseToml(rawSampleContent));
  const providers = parseIntegrationSandboxProviders(
    process.env.MISTLE_TEST_SANDBOX_INTEGRATION_PROVIDERS,
  );

  generateIntegrationConfigFiles({ providers, sampleConfigRoot, env: process.env });
}

try {
  main();
} catch (error) {
  if (error instanceof Error) {
    console.error(error.message);
  } else {
    console.error(String(error));
  }

  process.exitCode = 1;
}
