import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { loadConfig } from "../../packages/config/src/loader.ts";
import { AppIds } from "../../packages/config/src/modules.ts";
import {
  getRequiredIntegrationConfigValues,
  getIntegrationProviderPreset,
  parseIntegrationSandboxProviders,
  type IntegrationSandboxProvider,
} from "./presets/integration/index.ts";
import {
  applyTomlConfigEnvOverrides,
  buildIntegrationTomlConfig,
  getValueAtTomlConfigPath,
  isMissingRequiredConfigValue,
  stringifyTomlConfig,
  type ConfigRecord,
} from "./toml-config.ts";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..", "..");

function buildGeneratedHeader(provider: IntegrationSandboxProvider): string {
  return [
    "# Generated by `pnpm config:init:integration`.",
    "# Uses the resource-oriented TOML shape.",
    `# Sandbox provider: ${provider}.`,
    "",
  ].join("\n");
}

function assertRequiredConfigValues(input: {
  provider: IntegrationSandboxProvider;
  configRoot: ConfigRecord;
}): void {
  for (const requiredValue of getRequiredIntegrationConfigValues(input)) {
    const value = getValueAtTomlConfigPath(input.configRoot, requiredValue.path);
    if (isMissingRequiredConfigValue(value)) {
      throw new Error(
        `Missing required config value at ${requiredValue.path.join(".")} for provider "${input.provider}". Set ${requiredValue.envVar} before running \`pnpm config:init:integration\`.`,
      );
    }
  }
}

async function buildIntegrationConfig(input: {
  provider: IntegrationSandboxProvider;
  env: NodeJS.ProcessEnv;
}): Promise<ConfigRecord> {
  const preset = await getIntegrationProviderPreset(input.provider);
  const configRootInput = {
    provider: input.provider,
    environment: input.env,
    ...(preset.e2bSandboxBaseImage === undefined
      ? {}
      : { e2bSandboxBaseImage: preset.e2bSandboxBaseImage }),
  };
  const configRoot = buildIntegrationTomlConfig(configRootInput);
  const withEnvOverrides = applyTomlConfigEnvOverrides({
    configRoot,
    environment: input.env,
  });

  assertRequiredConfigValues({
    provider: input.provider,
    configRoot: withEnvOverrides,
  });

  return withEnvOverrides;
}

async function writeIntegrationConfig(input: {
  provider: IntegrationSandboxProvider;
  configRoot: ConfigRecord;
}): Promise<string> {
  const preset = await getIntegrationProviderPreset(input.provider);
  const targetPath = join(REPO_ROOT, "config", preset.outputFileName);
  const content = stringifyTomlConfig({
    header: buildGeneratedHeader(input.provider),
    configRoot: input.configRoot,
  });

  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, content, "utf8");
  return targetPath;
}

function validateWrittenIntegrationConfig(configPath: string): void {
  loadConfig({ app: AppIds.CONTROL_PLANE_API, configPath });
  loadConfig({ app: AppIds.CONTROL_PLANE_WORKER, configPath });
  loadConfig({ app: AppIds.DATA_PLANE_API, configPath });
  loadConfig({ app: AppIds.DATA_PLANE_GATEWAY, configPath });
  loadConfig({ app: AppIds.DATA_PLANE_WORKER, configPath });
  loadConfig({ app: AppIds.TOKENIZER_PROXY, configPath });
}

async function generateIntegrationConfigFiles(input: {
  providers: readonly IntegrationSandboxProvider[];
  env: NodeJS.ProcessEnv;
}): Promise<void> {
  for (const provider of input.providers) {
    const configRoot = await buildIntegrationConfig({
      provider,
      env: input.env,
    });
    const configPath = await writeIntegrationConfig({
      provider,
      configRoot,
    });
    validateWrittenIntegrationConfig(configPath);
    console.log(`Initialized integration config (${provider}): ${configPath}`);
  }
}

async function main(): Promise<void> {
  if (process.argv.length > 2) {
    throw new Error("This script does not accept arguments.");
  }

  const providers = parseIntegrationSandboxProviders(
    process.env.MISTLE_TEST_SANDBOX_INTEGRATION_PROVIDERS,
  );

  await generateIntegrationConfigFiles({ providers, env: process.env });
}

void main().catch((error: unknown) => {
  if (error instanceof Error) {
    console.error(error.message);
  } else {
    console.error(String(error));
  }

  process.exitCode = 1;
});
