import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseToml, stringify as stringifyToml } from "smol-toml";

/**
 * @typedef {Record<string, unknown>} ConfigRecord
 */

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..", "..");
const SAMPLE_PATH = join(REPO_ROOT, "config", "config.sample.toml");
const TARGET_PATH = join(REPO_ROOT, "config", "config.ci.toml");
const GENERATED_HEADER = [
  "# Generated by `pnpm config:init:ci`.",
  "# Regenerated by CI to provide build-time configuration.",
  "",
].join("\n");

/** @type {ConfigRecord} */
const CI_DEFAULTS = {
  global: {
    env: "production",
  },
  apps: {
    dashboard: {
      control_plane_api_origin: "https://api.mistle.example",
    },
  },
};

/**
 * @param {unknown} value
 * @returns {value is ConfigRecord}
 */
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * @param {unknown} value
 * @returns {ConfigRecord}
 */
function asRecord(value) {
  if (!isRecord(value)) {
    return {};
  }

  return value;
}

/**
 * @param {unknown} value
 * @returns {unknown}
 */
function deepClone(value) {
  if (Array.isArray(value)) {
    return value.map((item) => deepClone(item));
  }

  if (isRecord(value)) {
    return Object.fromEntries(
      Object.entries(value).map(([key, entryValue]) => [key, deepClone(entryValue)]),
    );
  }

  return value;
}

/**
 * @param {ConfigRecord} base
 * @param {ConfigRecord} override
 * @returns {ConfigRecord}
 */
function mergeRecords(base, override) {
  const merged = { ...base };

  for (const [key, overrideValue] of Object.entries(override)) {
    const baseValue = merged[key];

    if (isRecord(baseValue) && isRecord(overrideValue)) {
      merged[key] = mergeRecords(baseValue, overrideValue);
      continue;
    }

    merged[key] = deepClone(overrideValue);
  }

  return merged;
}

function main() {
  if (process.argv.length > 2) {
    throw new Error("This script does not accept arguments.");
  }

  if (!existsSync(SAMPLE_PATH)) {
    throw new Error(`Missing sample config file at: ${SAMPLE_PATH}`);
  }

  const sampleContent = readFileSync(SAMPLE_PATH, "utf8");
  const sampleConfig = asRecord(parseToml(sampleContent));
  const ciConfig = mergeRecords(sampleConfig, CI_DEFAULTS);
  const ciContent = `${GENERATED_HEADER}${stringifyToml(ciConfig)}`;

  mkdirSync(dirname(TARGET_PATH), { recursive: true });
  writeFileSync(TARGET_PATH, ciContent, "utf8");
  console.log(`Initialized CI config: ${TARGET_PATH}`);
}

try {
  main();
} catch (error) {
  if (error instanceof Error) {
    console.error(error.message);
  } else {
    console.error(String(error));
  }
  process.exitCode = 1;
}
