import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parse as parseToml, stringify as stringifyToml } from "smol-toml";

import type { ConfigRecord } from "./presets/development/types.ts";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..", "..");
const SAMPLE_PATH = join(REPO_ROOT, "config", "config.sample.toml");
const TARGET_PATH = join(REPO_ROOT, "config", "config.ci.toml");
const GENERATED_HEADER = [
  "# Generated by `pnpm config:init:ci`.",
  "# Regenerated by CI to provide build-time configuration.",
  "",
].join("\n");

const CI_DEFAULTS: ConfigRecord = {
  global: {
    env: "production",
  },
  apps: {
    dashboard: {
      control_plane_api_origin: "https://api.mistle.example",
    },
  },
};

function isRecord(value: unknown): value is ConfigRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function asRecord(value: unknown): ConfigRecord {
  if (!isRecord(value)) {
    return {};
  }

  return value;
}

function deepClone(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((item) => deepClone(item));
  }

  if (isRecord(value)) {
    const clonedEntries: [string, unknown][] = [];

    for (const [key, entryValue] of Object.entries(value)) {
      clonedEntries.push([key, deepClone(entryValue)]);
    }

    return Object.fromEntries(clonedEntries);
  }

  return value;
}

function mergeRecords(base: ConfigRecord, override: ConfigRecord): ConfigRecord {
  const merged: ConfigRecord = { ...base };

  for (const [key, overrideValue] of Object.entries(override)) {
    const baseValue = merged[key];

    if (isRecord(baseValue) && isRecord(overrideValue)) {
      merged[key] = mergeRecords(baseValue, overrideValue);
      continue;
    }

    merged[key] = deepClone(overrideValue);
  }

  return merged;
}

function main(): void {
  if (process.argv.length > 2) {
    throw new Error("This script does not accept arguments.");
  }

  if (!existsSync(SAMPLE_PATH)) {
    throw new Error(`Missing sample config file at: ${SAMPLE_PATH}`);
  }

  const sampleContent = readFileSync(SAMPLE_PATH, "utf8");
  const sampleConfig = asRecord(parseToml(sampleContent));
  const ciConfig = mergeRecords(sampleConfig, CI_DEFAULTS);
  const ciContent = `${GENERATED_HEADER}${stringifyToml(ciConfig)}`;

  mkdirSync(dirname(TARGET_PATH), { recursive: true });
  writeFileSync(TARGET_PATH, ciContent, "utf8");
  console.log(`Initialized CI config: ${TARGET_PATH}`);
}

try {
  main();
} catch (error) {
  if (error instanceof Error) {
    console.error(error.message);
  } else {
    console.error(String(error));
  }
  process.exitCode = 1;
}
