version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    commit-message:
      prefix: chore(deps)
  - package-ecosystem: npm
    directory: "/tests/system/fixtures/vite-dev-server"
    schedule:
      interval: daily
    versioning-strategy: increase
    commit-message:
      prefix: chore(deps)
  - package-ecosystem: cargo
    directory: "/packages/sandboxd"
    schedule:
      interval: daily
    commit-message:
      prefix: chore(deps)
  - package-ecosystem: cargo
    directory: "/packages/commit-sign"
    schedule:
      interval: daily
    commit-message:
      prefix: chore(deps)
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: chore(deps)
