packages:
  - apps/*
  - packages/*
  - tests

# 3 days = 4320 minutes.
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@opencode-ai/sdk"

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - squawk-cli
