#!/bin/sh
set -eu

cd /app

node /app/node_modules/@mistle/control-plane-api/dist/scripts/run-control-plane-migrations.js
node /app/node_modules/@mistle/control-plane-api/dist/scripts/run-control-plane-workflow-migrations.js
node /app/node_modules/@mistle/data-plane-api/dist/scripts/run-data-plane-migrations.js
node /app/node_modules/@mistle/data-plane-api/dist/scripts/run-data-plane-workflow-migrations.js
