export const AwsEndpointCatalog = {
  partition: "aws",
  dnsSuffix: "amazonaws.com",
  regionIds: [
    "af-south-1",
    "ap-east-1",
    "ap-east-2",
    "ap-northeast-1",
    "ap-northeast-2",
    "ap-northeast-3",
    "ap-south-1",
    "ap-south-2",
    "ap-southeast-1",
    "ap-southeast-2",
    "ap-southeast-3",
    "ap-southeast-4",
    "ap-southeast-5",
    "ap-southeast-6",
    "ap-southeast-7",
    "ca-central-1",
    "ca-west-1",
    "eu-central-1",
    "eu-central-2",
    "eu-north-1",
    "eu-south-1",
    "eu-south-2",
    "eu-west-1",
    "eu-west-2",
    "eu-west-3",
    "il-central-1",
    "me-central-1",
    "me-south-1",
    "mx-central-1",
    "sa-east-1",
    "us-east-1",
    "us-east-2",
    "us-west-1",
    "us-west-2",
  ],
  serviceIds: [
    "access-analyzer",
    "account",
    "acm",
    "acm-pca",
    "agreement-marketplace",
    "airflow",
    "amplify",
    "amplifybackend",
    "amplifyuibuilder",
    "aoss",
    "api.detective",
    "api.ecr",
    "api.ecr-public",
    "api.iotdeviceadvisor",
    "api.iotwireless",
    "api.mediatailor",
    "api.pricing",
    "api.sagemaker",
    "api.tunneling.iot",
    "apigateway",
    "app-integrations",
    "appconfig",
    "appconfigdata",
    "appflow",
    "application-autoscaling",
    "applicationinsights",
    "appmesh",
    "apprunner",
    "appstream2",
    "appsync",
    "aps",
    "arc-zonal-shift",
    "athena",
    "auditmanager",
    "autoscaling",
    "autoscaling-plans",
    "backup",
    "backup-gateway",
    "batch",
    "bedrock",
    "billingconductor",
    "braket",
    "budgets",
    "cases",
    "cassandra",
    "catalog.marketplace",
    "ce",
    "chime",
    "cleanrooms",
    "cloud9",
    "cloudcontrolapi",
    "clouddirectory",
    "cloudformation",
    "cloudfront",
    "cloudhsm",
    "cloudhsmv2",
    "cloudsearch",
    "cloudtrail",
    "cloudtrail-data",
    "codeartifact",
    "codebuild",
    "codecatalyst",
    "codecommit",
    "codedeploy",
    "codeguru-profiler",
    "codeguru-reviewer",
    "codepipeline",
    "codestar-connections",
    "codestar-notifications",
    "cognito-identity",
    "cognito-idp",
    "cognito-sync",
    "comprehend",
    "comprehendmedical",
    "compute-optimizer",
    "config",
    "connect",
    "connect-campaigns",
    "contact-lens",
    "controltower",
    "cost-optimization-hub",
    "cur",
    "data-ats.iot",
    "data.iot",
    "data.jobs.iot",
    "data.mediastore",
    "databrew",
    "dataexchange",
    "datapipeline",
    "datasync",
    "datazone",
    "dax",
    "devicefarm",
    "devops-guru",
    "directconnect",
    "discovery",
    "dlm",
    "dms",
    "docdb",
    "drs",
    "ds",
    "dynamodb",
    "ebs",
    "ec2",
    "ecs",
    "edge.sagemaker",
    "eks",
    "eks-auth",
    "elasticache",
    "elasticbeanstalk",
    "elasticfilesystem",
    "elasticloadbalancing",
    "elasticmapreduce",
    "email",
    "emr-containers",
    "emr-serverless",
    "entitlement.marketplace",
    "es",
    "events",
    "finspace",
    "finspace-api",
    "firehose",
    "fms",
    "forecast",
    "forecastquery",
    "frauddetector",
    "fsx",
    "gamelift",
    "gameliftstreams",
    "geo",
    "glacier",
    "globalaccelerator",
    "glue",
    "grafana",
    "greengrass",
    "groundstation",
    "guardduty",
    "health",
    "healthlake",
    "iam",
    "identity-chime",
    "identitystore",
    "importexport",
    "ingest.timestream",
    "inspector",
    "inspector2",
    "internetmonitor",
    "iot",
    "iotevents",
    "ioteventsdata",
    "iotfleetwise",
    "iotsecuredtunneling",
    "iotsitewise",
    "iotthingsgraph",
    "iottwinmaker",
    "iotwireless",
    "ivs",
    "ivschat",
    "ivsrealtime",
    "kafka",
    "kafkaconnect",
    "kendra",
    "kendra-ranking",
    "kinesis",
    "kinesisanalytics",
    "kinesisvideo",
    "kms",
    "lakeformation",
    "lambda",
    "license-manager",
    "license-manager-linux-subscriptions",
    "license-manager-user-subscriptions",
    "lightsail",
    "logs",
    "lookoutequipment",
    "m2",
    "machinelearning",
    "macie2",
    "managedblockchain",
    "managedblockchain-query",
    "marketplacecommerceanalytics",
    "media-pipelines-chime",
    "mediaconnect",
    "mediaconvert",
    "medialive",
    "mediapackage",
    "mediapackage-vod",
    "mediapackagev2",
    "mediastore",
    "meetings-chime",
    "memory-db",
    "messaging-chime",
    "metering.marketplace",
    "metrics.sagemaker",
    "mgh",
    "mgn",
    "migrationhub-orchestrator",
    "migrationhub-strategy",
    "mobileanalytics",
    "models-v2-lex",
    "models.lex",
    "monitoring",
    "mq",
    "mturk-requester",
    "neptune",
    "network-firewall",
    "networkmanager",
    "notifications",
    "notifications-contacts",
    "nova-act",
    "oam",
    "oidc",
    "omics",
    "organizations",
    "osis",
    "outposts",
    "participant.connect",
    "partnercentral-channel",
    "personalize",
    "pi",
    "pinpoint",
    "pipes",
    "polly",
    "portal.sso",
    "profile",
    "proton",
    "qbusiness",
    "query.timestream",
    "quicksight",
    "ram",
    "rbin",
    "rds",
    "rds-data",
    "redshift",
    "redshift-serverless",
    "rekognition",
    "resiliencehub",
    "resource-explorer-2",
    "resource-groups",
    "rolesanywhere",
    "route53",
    "route53-recovery-control-config",
    "route53domains",
    "route53profiles",
    "route53resolver",
    "rum",
    "runtime-v2-lex",
    "runtime.lex",
    "runtime.sagemaker",
    "s3",
    "s3-control",
    "s3-outposts",
    "sagemaker-geospatial",
    "savingsplans",
    "scheduler",
    "schemas",
    "sdb",
    "secretsmanager",
    "securityhub",
    "securitylake",
    "serverlessrepo",
    "servicecatalog",
    "servicecatalog-appregistry",
    "servicediscovery",
    "servicequotas",
    "shield",
    "signer",
    "simspaceweaver",
    "sms-voice",
    "snowball",
    "sns",
    "sqs",
    "ssm",
    "ssm-contacts",
    "ssm-incidents",
    "ssm-quicksetup",
    "ssm-sap",
    "sso",
    "states",
    "storagegateway",
    "streams.dynamodb",
    "sts",
    "support",
    "supportapp",
    "swf",
    "synthetics",
    "tagging",
    "tax",
    "textract",
    "thinclient",
    "tnb",
    "transcribe",
    "transcribestreaming",
    "transfer",
    "translate",
    "trustedadvisor",
    "verifiedpermissions",
    "voice-chime",
    "voiceid",
    "vpc-lattice",
    "waf",
    "waf-regional",
    "wafv2",
    "wellarchitected",
    "wisdom",
    "workdocs",
    "workmail",
    "workspaces",
    "workspaces-web",
    "xray",
  ],
  endpointMetadata: {
    account: {
      regionalized: false,
      hostname: "account.us-east-1.amazonaws.com",
      signingRegion: "us-east-1",
    },
    billingconductor: {
      regionalized: false,
      hostname: "billingconductor.us-east-1.amazonaws.com",
      signingRegion: "us-east-1",
    },
    budgets: {
      regionalized: false,
      hostname: "budgets.amazonaws.com",
      signingRegion: "us-east-1",
    },
    ce: {
      regionalized: false,
      hostname: "ce.us-east-1.amazonaws.com",
      signingRegion: "us-east-1",
    },
    chime: {
      regionalized: false,
      hostname: "chime.us-east-1.amazonaws.com",
      signingRegion: "us-east-1",
    },
    cloudfront: {
      regionalized: false,
      hostname: "cloudfront.amazonaws.com",
      signingRegion: "us-east-1",
    },
    codecatalyst: {
      regionalized: false,
      hostname: "codecatalyst.global.api.aws",
    },
    health: {
      regionalized: false,
      hostname: "global.health.amazonaws.com",
      signingRegion: "us-east-1",
    },
    iam: {
      regionalized: false,
      hostname: "iam.amazonaws.com",
      signingRegion: "us-east-1",
    },
    importexport: {
      regionalized: false,
      hostname: "importexport.amazonaws.com",
      signingRegion: "us-east-1",
    },
    "mturk-requester": {
      regionalized: false,
    },
    networkmanager: {
      regionalized: false,
      hostname: "networkmanager.us-west-2.amazonaws.com",
      signingRegion: "us-west-2",
    },
    "notifications-contacts": {
      regionalized: false,
      hostname: "notifications-contacts.us-east-1.api.aws",
      signingRegion: "us-east-1",
    },
    organizations: {
      regionalized: false,
      hostname: "organizations.us-east-1.amazonaws.com",
      signingRegion: "us-east-1",
    },
    route53: {
      regionalized: false,
      hostname: "route53.amazonaws.com",
      signingRegion: "us-east-1",
    },
    s3: {
      regionalized: true,
      hostname: "s3.amazonaws.com",
      signingRegion: "us-east-1",
    },
    savingsplans: {
      regionalized: false,
      hostname: "savingsplans.amazonaws.com",
      signingRegion: "us-east-1",
    },
    shield: {
      regionalized: false,
      hostname: "shield.us-east-1.amazonaws.com",
      signingRegion: "us-east-1",
    },
    sts: {
      regionalized: true,
      hostname: "sts.amazonaws.com",
      signingRegion: "us-east-1",
    },
    support: {
      regionalized: true,
      hostname: "support.us-east-1.amazonaws.com",
      signingRegion: "us-east-1",
    },
    tax: {
      regionalized: false,
      hostname: "tax.us-east-1.amazonaws.com",
      signingRegion: "us-east-1",
    },
    waf: {
      regionalized: false,
      hostname: "waf.amazonaws.com",
      signingRegion: "us-east-1",
    },
  },
} as const;
