import { spawnSync } from "node:child_process";
import { constants } from "node:fs";
import { access, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { compileFromFile } from "json-schema-to-typescript";

function resolvePaths(): {
  sandboxRuntimeRoot: string;
  generatedTypesPath: string;
} {
  const scriptPath = fileURLToPath(import.meta.url);
  const scriptsDirectory = dirname(scriptPath);
  const dashboardRoot = resolve(scriptsDirectory, "..");
  const workspaceRoot = resolve(dashboardRoot, "../..");

  return {
    sandboxRuntimeRoot: resolve(workspaceRoot, "apps/sandbox-runtime"),
    generatedTypesPath: resolve(
      dashboardRoot,
      "src/lib/sandbox-session-protocol/generated/types.ts",
    ),
  };
}

function runSandboxSessionProtocolSchemaGenerator(input: {
  sandboxRuntimeRoot: string;
  schemaOutputPath: string;
}): void {
  const result = spawnSync(
    "go",
    ["run", "./cmd/sandbox-session-protocol-schema", "-out", input.schemaOutputPath],
    {
      cwd: input.sandboxRuntimeRoot,
      encoding: "utf8",
      stdio: "pipe",
    },
  );

  if (result.error !== undefined) {
    throw result.error;
  }

  if ((result.status ?? 1) !== 0) {
    throw new Error(
      [
        "sandbox session protocol schema generation failed.",
        result.stderr.trim(),
        result.stdout.trim(),
      ]
        .filter((line) => line.length > 0)
        .join("\n"),
    );
  }
}

async function generateTypesFromSchema(input: {
  schemaPath: string;
  outputPath: string;
}): Promise<void> {
  const source = await compileFromFile(input.schemaPath, {
    bannerComment:
      "/* This file was auto-generated by scripts/sandbox-session-protocol-client.ts. Do not edit manually. */",
    additionalProperties: false,
    enableConstEnums: false,
    strictIndexSignatures: true,
  });

  await writeFile(input.outputPath, source, "utf8");
}

function runOxfmt(outputPath: string): void {
  const result = spawnSync("pnpm", ["exec", "oxfmt", outputPath], {
    encoding: "utf8",
    stdio: "pipe",
  });

  if (result.error !== undefined) {
    throw result.error;
  }

  if ((result.status ?? 1) !== 0) {
    throw new Error(
      [
        "oxfmt formatting failed for generated sandbox session protocol types.",
        result.stderr.trim(),
        result.stdout.trim(),
      ]
        .filter((line) => line.length > 0)
        .join("\n"),
    );
  }
}

export async function generateSandboxSessionProtocolTypesFile(): Promise<{
  generatedTypesPath: string;
}> {
  const { sandboxRuntimeRoot, generatedTypesPath } = resolvePaths();
  await access(sandboxRuntimeRoot, constants.R_OK);

  const temporaryDirectory = await mkdtemp(resolve(tmpdir(), "mistle-sandbox-session-schema-"));
  const schemaPath = resolve(temporaryDirectory, "sandbox-session-control.schema.json");

  try {
    runSandboxSessionProtocolSchemaGenerator({
      sandboxRuntimeRoot,
      schemaOutputPath: schemaPath,
    });
    await generateTypesFromSchema({
      schemaPath,
      outputPath: generatedTypesPath,
    });
    runOxfmt(generatedTypesPath);
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }

  return {
    generatedTypesPath,
  };
}

export async function generateSandboxSessionProtocolTypesToTemporarySource(): Promise<{
  generatedTypesPath: string;
  schemaSource: string;
}> {
  const { sandboxRuntimeRoot, generatedTypesPath } = resolvePaths();
  await access(sandboxRuntimeRoot, constants.R_OK);

  const temporaryDirectory = await mkdtemp(resolve(tmpdir(), "mistle-sandbox-session-types-"));
  const schemaPath = resolve(temporaryDirectory, "sandbox-session-control.schema.json");
  const outputPath = resolve(temporaryDirectory, "types.ts");

  try {
    runSandboxSessionProtocolSchemaGenerator({
      sandboxRuntimeRoot,
      schemaOutputPath: schemaPath,
    });
    await generateTypesFromSchema({
      schemaPath,
      outputPath,
    });
    runOxfmt(outputPath);

    const schemaSource = await readFile(outputPath, "utf8");
    return {
      generatedTypesPath,
      schemaSource,
    };
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
}

export async function readGeneratedTypesFile(generatedTypesPath: string): Promise<string | null> {
  try {
    return await readFile(generatedTypesPath, "utf8");
  } catch (error: unknown) {
    if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") {
      return null;
    }

    throw error;
  }
}
