export const IdentityLinkingBadRequestCodes = {
  INVALID_PROVIDER_CONFIG_INPUT: "INVALID_PROVIDER_CONFIG_INPUT",
  INVALID_LINKED_ACCOUNT_START_INPUT: "INVALID_LINKED_ACCOUNT_START_INPUT",
  INVALID_LINKED_ACCOUNT_CALLBACK_INPUT: "INVALID_LINKED_ACCOUNT_CALLBACK_INPUT",
  INVALID_LINKED_ACCOUNT_PREFERRED_EMAIL_INPUT: "INVALID_LINKED_ACCOUNT_PREFERRED_EMAIL_INPUT",
  PROVIDER_ADAPTER_NOT_IMPLEMENTED: "PROVIDER_ADAPTER_NOT_IMPLEMENTED",
  REDIRECT_STATE_INVALID: "REDIRECT_STATE_INVALID",
  REDIRECT_STATE_EXPIRED: "REDIRECT_STATE_EXPIRED",
  REDIRECT_STATE_ALREADY_USED: "REDIRECT_STATE_ALREADY_USED",
  PROVIDER_SUBJECT_ALREADY_LINKED: "PROVIDER_SUBJECT_ALREADY_LINKED",
} as const;

export const IdentityLinkingNotFoundCodes = {
  PROVIDER_NOT_FOUND: "PROVIDER_NOT_FOUND",
  PROVIDER_CONFIG_NOT_FOUND: "PROVIDER_CONFIG_NOT_FOUND",
  CONNECTION_NOT_FOUND: "CONNECTION_NOT_FOUND",
  LINKED_ACCOUNT_NOT_FOUND: "LINKED_ACCOUNT_NOT_FOUND",
} as const;
