export const INTEGRATION_CONNECTIONS_ROUTE_BASE_PATH = "/v1/integration/connections";

export const IntegrationConnectionsBadRequestCodes = {
  INVALID_LIST_CONNECTIONS_INPUT: "INVALID_LIST_CONNECTIONS_INPUT",
  INVALID_PAGINATION_CURSOR: "INVALID_PAGINATION_CURSOR",
  INVALID_LIST_CONNECTION_RESOURCES_INPUT: "INVALID_LIST_CONNECTION_RESOURCES_INPUT",
  INVALID_RESOURCE_PAGINATION_CURSOR: "INVALID_RESOURCE_PAGINATION_CURSOR",
  RESOURCE_KIND_NOT_SUPPORTED: "RESOURCE_KIND_NOT_SUPPORTED",
  INVALID_CREATE_CONNECTION_INPUT: "INVALID_CREATE_CONNECTION_INPUT",
  INVALID_UPDATE_CONNECTION_INPUT: "INVALID_UPDATE_CONNECTION_INPUT",
  API_KEY_NOT_SUPPORTED: "API_KEY_NOT_SUPPORTED",
  API_KEY_CONNECTION_REQUIRED: "API_KEY_CONNECTION_REQUIRED",
  INVALID_GITHUB_APP_INSTALLATION_START_INPUT: "INVALID_GITHUB_APP_INSTALLATION_START_INPUT",
  INVALID_GITHUB_APP_INSTALLATION_COMPLETE_INPUT: "INVALID_GITHUB_APP_INSTALLATION_COMPLETE_INPUT",
  GITHUB_APP_INSTALLATION_NOT_SUPPORTED: "GITHUB_APP_INSTALLATION_NOT_SUPPORTED",
  GITHUB_APP_INSTALLATION_HANDLER_NOT_CONFIGURED: "GITHUB_APP_INSTALLATION_HANDLER_NOT_CONFIGURED",
  INVALID_OAUTH2_START_INPUT: "INVALID_OAUTH2_START_INPUT",
  INVALID_OAUTH2_COMPLETE_INPUT: "INVALID_OAUTH2_COMPLETE_INPUT",
  OAUTH2_NOT_SUPPORTED: "OAUTH2_NOT_SUPPORTED",
  OAUTH2_CAPABILITY_NOT_CONFIGURED: "OAUTH2_CAPABILITY_NOT_CONFIGURED",
  REDIRECT_STATE_INVALID: "REDIRECT_STATE_INVALID",
  REDIRECT_STATE_EXPIRED: "REDIRECT_STATE_EXPIRED",
  REDIRECT_STATE_ALREADY_USED: "REDIRECT_STATE_ALREADY_USED",
} as const;

export const IntegrationConnectionsNotFoundCodes = {
  TARGET_NOT_FOUND: "TARGET_NOT_FOUND",
  CONNECTION_NOT_FOUND: "CONNECTION_NOT_FOUND",
} as const;

export const IntegrationConnectionsConflictCodes = {
  RESOURCE_SYNC_REQUIRED: "RESOURCE_SYNC_REQUIRED",
  RESOURCE_SYNC_IN_PROGRESS: "RESOURCE_SYNC_IN_PROGRESS",
  RESOURCE_SYNC_FAILED: "RESOURCE_SYNC_FAILED",
  CONNECTION_HAS_BINDINGS: "CONNECTION_HAS_BINDINGS",
} as const;
