import {
  createOAuth2AuthorizationCodeCredentialSlotKeys,
  IntegrationConnectionMethodIds,
} from "@mistle/integrations-core";
import { z } from "zod";

export const PostHogFamilyId = "posthog";
export const PostHogMcpVariantId = "posthog-mcp";
export const PostHogOAuthIssuerUrl = "https://oauth.posthog.com";
export const PostHogMcpUrl = "https://mcp.posthog.com/mcp";

export const PostHogCredentialSecretTypes: {
  OAUTH2_ACCESS_TOKEN: "oauth2_access_token";
} = {
  OAUTH2_ACCESS_TOKEN: "oauth2_access_token",
};

export const PostHogCredentialSlotKeys = createOAuth2AuthorizationCodeCredentialSlotKeys({
  familyId: PostHogFamilyId,
  variantId: PostHogMcpVariantId,
});

export const PostHogMcpOAuthScopes = [
  "openid",
  "profile",
  "email",
  "action:read",
  "action:write",
  "account:read",
  "account:write",
  "activity_log:read",
  "alert:read",
  "alert:write",
  "annotation:read",
  "annotation:write",
  "approvals:read",
  "batch_export:read",
  "batch_export:write",
  "business_knowledge:read",
  "business_knowledge:write",
  "cohort:read",
  "cohort:write",
  "comment:read",
  "dashboard:read",
  "dashboard:write",
  "early_access_feature:read",
  "early_access_feature:write",
  "endpoint:read",
  "endpoint:write",
  "engineering_analytics:read",
  "error_tracking:read",
  "error_tracking:write",
  "evaluation:read",
  "evaluation:write",
  "event_definition:read",
  "event_definition:write",
  "experiment:read",
  "experiment:write",
  "experiment_saved_metric:read",
  "experiment_saved_metric:write",
  "external_data_source:read",
  "external_data_source:write",
  "feature_flag:read",
  "feature_flag:write",
  "file_system:read",
  "file_system:write",
  "group:read",
  "health_issue:read",
  "heatmap:read",
  "heatmap:write",
  "hog_flow:read",
  "hog_flow:write",
  "hog_function:read",
  "hog_function:write",
  "insight:read",
  "insight:write",
  "insight_variable:read",
  "insight_variable:write",
  "integration:read",
  "integration:write",
  "llm_analytics:read",
  "llm_analytics:write",
  "llm_prompt:read",
  "llm_prompt:write",
  "llm_skill:read",
  "llm_skill:write",
  "logs:read",
  "logs:write",
  "marketing_analytics:read",
  "notebook:read",
  "notebook:write",
  "organization:read",
  "organization:write",
  "organization_member:read",
  "person:read",
  "person:write",
  "project:read",
  "project:write",
  "property_definition:read",
  "query:read",
  "replay_scanner:read",
  "replay_scanner:write",
  "session_recording:read",
  "session_recording:write",
  "session_recording_playlist:read",
  "session_recording_playlist:write",
  "signal_scout:read",
  "signal_scout:write",
  "subscription:read",
  "subscription:write",
  "survey:read",
  "survey:write",
  "tagger:read",
  "tagger:write",
  "ticket:read",
  "ticket:write",
  "task:read",
  "task:write",
  "tracing:read",
  "field_note:read",
  "field_note:write",
  "usage_metric:read",
  "usage_metric:write",
  "user:read",
  "user:write",
  "user_interview:read",
  "user_interview:write",
  "visual_review:read",
  "visual_review:write",
  "warehouse_table:read",
  "warehouse_view:read",
  "warehouse_view:write",
  "web_analytics:read",
];

export const PostHogConnectionConfigSchema = z
  .object({
    connection_method: z.literal(IntegrationConnectionMethodIds.OAUTH2_AUTHORIZATION_CODE),
    client_id: z.string().min(1),
  })
  .strict();

export type PostHogConnectionConfig = z.output<typeof PostHogConnectionConfigSchema>;
