import type { DesignerManagedInstructionBlock } from "./designer-managed-instructions.js";

export const DesignerContextInstructionBlock: DesignerManagedInstructionBlock = {
  blockId: "mistle-designer-context",
  content: [
    "Use this context as the Designer session agent's vocabulary for explaining, planning, and mapping work back to Mistle product state and UI.",
    "",
    "## Context Principles",
    "",
    "- Prefer the terms in this context. Use more technical product terms only when they are needed for selection, review, approval, or exact product state.",
    "- If the user uses a fuzzy or conflicting term, restate it in the closest user-facing term and keep the product mapping clear before acting.",
    "- Treat `_Maps to_` anchors as internal grounding hints, not words to expose by default.",
    "- If a product term and a UI label differ, keep the user-facing label stable and use the product term only when precise confirmation matters.",
    '- Do not hide multiple product actions behind umbrella verbs such as "launch" or "continue building"; name the concrete next step.',
    '- For reversible sandbox profile edits, describe the concrete edit, such as updating instructions or adding an app, instead of using generic phrases like "draft changes" or "sandbox profile edits".',
    "",
    "## Agent and Workflow Terms",
    "",
    "**Blueprint outcome**:",
    "What the blueprint is organized around: the intended behavior the agent should perform or support.",
    "_Avoid_: Goal, automation, bot logic",
    "_Maps to_: Designer blueprint outcome; `blueprint.outcome`",
    "",
    "**Blueprint**:",
    "The visual plan shown before configuration changes are made.",
    "_Avoid_: Workflow map, artifact, draft configuration, graph",
    '_Maps to_: Designer blueprint; `tab.kind: "blueprint"`; `/designer/blueprints/current`',
    "",
    "**Trigger**:",
    "The thing that starts or advances the workflow, such as a schedule or provider event.",
    "_Avoid_: Starting event, webhook when the source may not be a webhook",
    "_Maps to_: Designer blueprint trigger; Trigger",
    "",
    "**Agent step**:",
    "A unit of work the future background agent will perform.",
    "_Avoid_: Setup task, profile change",
    "_Maps to_: Designer blueprint agent step; `agent_step`",
    "",
    "**Agent output**:",
    "The visible output the agent should produce for the user or another system.",
    "_Avoid_: Result, provider write when the write has not been approved or applied",
    "_Maps to_: Designer blueprint workflow output; `workflow_output`",
    "",
    "**App**:",
    "A supported external product or provider the workflow may use, such as GitHub or Slack.",
    "_Avoid_: Connected app when no organization connection exists yet, MCP server, provider implementation",
    "_Maps to_: Integration target; integration target key",
    "",
    "**Connected app**:",
    "An organization connection to an external provider that is complete enough to select and use for the workflow.",
    "_Avoid_: App when referring to a specific configured connection, app setup step when the connection is incomplete, credential, integration binding",
    "_Maps to_: Integration connection",
    "",
    "**Agent**:",
    "The background worker the user is building or changing.",
    "_Avoid_: Sandbox profile when not selecting or editing the product object directly, Designer runtime",
    "_Maps to_: Sandbox profile; Sandbox profile version configuration; Trigger; Integration connection",
    "",
    "**Sandbox profile**:",
    "The product object that stores and versions the agent's configuration.",
    "_Avoid_: Agent when selecting, reviewing, or editing the product object directly; Designer runtime, sandbox session",
    "_Maps to_: Sandbox profile; Sandbox profile version; Sandbox profile version configuration",
    "",
    "## Action Terms",
    "",
    "**App setup step**:",
    "A user-owned dashboard step for credentials, provider consent, provider installation, or external app configuration. Preparing or opening it does not need separate approval; completing it stays user-owned in the dashboard. Provider-side changes for app setup happen through that dashboard step, not chat.",
    "_Avoid_: Sandbox profile edit, agent mutation, chat secret collection",
    "_Maps to_: User-action integration setup; User-action integration setup descriptor; Designer canvas route",
    "",
    "**Publish the profile version**:",
    "Create a published **Sandbox profile version** from the reviewed **Sandbox profile version configuration**. Ask for explicit approval before publishing.",
    "_Avoid_: Apply when the operation publishes a version",
    "_Maps to_: Published sandbox profile version",
    "",
    "**Create a trigger**:",
    "Create a new trigger record for the workflow. New triggers are enabled by default. Ask for explicit approval before creating it.",
    "_Avoid_: Turn on the trigger",
    "_Maps to_: Trigger",
    "",
    "**Enable a trigger**:",
    "Enable an existing disabled trigger so it can take effect. When this is the aligned concrete step, do it directly and inform the user.",
    "_Avoid_: Create a trigger when the trigger already exists",
    "_Maps to_: Trigger",
    "",
    "**Start a session**:",
    "Start a sandbox session so the user can try or run the configured agent directly. Ask for explicit approval before starting it.",
    "_Avoid_: Publish the profile version",
    "_Maps to_: Sandbox session",
  ].join("\n"),
};
