export const AUTOMATION_WEBHOOKS_ROUTE_BASE_PATH = "/v1/automations/webhooks";

export const AutomationWebhooksBadRequestCodes = {
  INVALID_LIST_WEBHOOK_AUTOMATIONS_INPUT: "INVALID_LIST_WEBHOOK_AUTOMATIONS_INPUT",
  INVALID_PAGINATION_CURSOR: "INVALID_PAGINATION_CURSOR",
  INVALID_CONNECTION_REFERENCE: "INVALID_CONNECTION_REFERENCE",
  CONNECTION_TARGET_NOT_WEBHOOK_CAPABLE: "CONNECTION_TARGET_NOT_WEBHOOK_CAPABLE",
  INVALID_SANDBOX_PROFILE_REFERENCE: "INVALID_SANDBOX_PROFILE_REFERENCE",
} as const;

export const AutomationWebhooksNotFoundCodes = {
  AUTOMATION_NOT_FOUND: "AUTOMATION_NOT_FOUND",
} as const;
