export const AUTOMATION_WEBHOOKS_ROUTE_BASE_PATH = "/v1/automations/webhooks";

export const AutomationWebhooksBadRequestCodes = {
  INVALID_LIST_WEBHOOK_AUTOMATIONS_INPUT: "INVALID_LIST_WEBHOOK_AUTOMATIONS_INPUT",
  INVALID_PAGINATION_CURSOR: "INVALID_PAGINATION_CURSOR",
  INVALID_WEBHOOK_SOURCE_REFERENCE: "INVALID_WEBHOOK_SOURCE_REFERENCE",
  WEBHOOK_SOURCE_TARGET_NOT_WEBHOOK_CAPABLE: "WEBHOOK_SOURCE_TARGET_NOT_WEBHOOK_CAPABLE",
  INVALID_SANDBOX_PROFILE_REFERENCE: "INVALID_SANDBOX_PROFILE_REFERENCE",
  INVALID_SANDBOX_PROFILE_TRIGGER_REFERENCE: "INVALID_SANDBOX_PROFILE_TRIGGER_REFERENCE",
  INVALID_PRIMARY_REPOSITORY: "INVALID_PRIMARY_REPOSITORY",
} as const;
