import type { OrganizationUsageSettingsPageViewProps } from "./organization-usage-settings-page-view.js";

export function createOrganizationUsagePrototypeProps(): OrganizationUsageSettingsPageViewProps {
  return {
    period: {
      range: "June 1-29, 2026",
    },
    summaryMetrics: [
      {
        id: "sandbox-hours",
        label: "Sandbox hours",
        value: "312.4h",
      },
      {
        id: "sandbox-runs",
        label: "Sandbox runs",
        value: "186",
      },
      {
        id: "vcpu-hours",
        label: "vCPU hours",
        value: "784.2",
      },
      {
        id: "memory-gb-hours",
        label: "Memory GB-hours",
        value: "2,109.6",
      },
      {
        id: "storage-gb-hours",
        label: "Storage GB-hours",
        value: "8,812.8",
      },
    ],
    dailyUsage: [
      { day: "Jun 1", sandboxHours: 7.4, runCount: 5 },
      { day: "Jun 4", sandboxHours: 12.8, runCount: 9 },
      { day: "Jun 7", sandboxHours: 18.6, runCount: 11 },
      { day: "Jun 10", sandboxHours: 9.7, runCount: 7 },
      { day: "Jun 13", sandboxHours: 21.9, runCount: 14 },
      { day: "Jun 16", sandboxHours: 34.2, runCount: 18 },
      { day: "Jun 19", sandboxHours: 28.4, runCount: 16 },
      { day: "Jun 22", sandboxHours: 45.8, runCount: 21 },
      { day: "Jun 25", sandboxHours: 39.1, runCount: 19 },
      { day: "Jun 28", sandboxHours: 33.6, runCount: 17 },
    ],
    profileBreakdown: [
      {
        id: "profile-pr-review",
        label: "PR review agent",
        sandboxHours: 128.2,
        vcpuHours: 512.8,
        memoryGbHours: 1_025.6,
        storageGbHours: 5_128,
        sharePercent: 41,
        runCount: 75,
      },
      {
        id: "profile-designer",
        label: "Mistle Designer",
        sandboxHours: 82.7,
        vcpuHours: 165.4,
        memoryGbHours: 330.8,
        storageGbHours: 1_654,
        sharePercent: 26,
        runCount: 39,
      },
      {
        id: "profile-release",
        label: "Release checklist agent",
        sandboxHours: 57.5,
        vcpuHours: 115,
        memoryGbHours: 460,
        storageGbHours: 1_150,
        sharePercent: 18,
        runCount: 18,
      },
      {
        id: "profile-research",
        label: "Research assistant",
        sandboxHours: 44,
        vcpuHours: 88,
        memoryGbHours: 293.2,
        storageGbHours: 880,
        sharePercent: 14,
        runCount: 34,
      },
    ],
    activityBreakdown: [
      {
        id: "activity-user-sessions",
        label: "User sessions",
        sandboxHours: 186.5,
        vcpuHours: 420.4,
        memoryGbHours: 1_104.1,
        storageGbHours: 3_982,
        sharePercent: 60,
        runCount: 159,
      },
      {
        id: "activity-trigger-runs",
        label: "Trigger runs",
        sandboxHours: 79.4,
        vcpuHours: 317.6,
        memoryGbHours: 635.2,
        storageGbHours: 3_176,
        sharePercent: 25,
        runCount: 29,
      },
      {
        id: "activity-setup-assistants",
        label: "Setup assistants",
        sandboxHours: 31.2,
        vcpuHours: 62.4,
        memoryGbHours: 249.6,
        storageGbHours: 624,
        sharePercent: 10,
        runCount: 8,
      },
      {
        id: "activity-setup-script-checks",
        label: "Setup script checks",
        sandboxHours: 9.8,
        vcpuHours: 19.6,
        memoryGbHours: 78.4,
        storageGbHours: 196,
        sharePercent: 3,
        runCount: 9,
      },
      {
        id: "activity-snapshot-maintenance",
        label: "Snapshot maintenance",
        sandboxHours: 5.5,
        vcpuHours: 11,
        memoryGbHours: 42.3,
        storageGbHours: 110,
        sharePercent: 2,
        runCount: 5,
      },
    ],
  };
}
