export const DESIGNER_ROUTE_BASE_PATH = "/v1/designer";

export const DESIGNER_RUNTIME_PROFILE_ID = "designer";
export const DESIGNER_RUNTIME_PROFILE_VERSION = 1;

export const DesignerBadRequestCodes = {
  DESIGNER_INITIAL_PROMPT_MISSING: "DESIGNER_INITIAL_PROMPT_MISSING",
  DESIGNER_SANDBOX_RUNTIME_UNAVAILABLE: "DESIGNER_SANDBOX_RUNTIME_UNAVAILABLE",
} as const;

export const DesignerConflictCodes = {
  DESIGNER_ACTION_PROPOSAL_NOT_PENDING: "DESIGNER_ACTION_PROPOSAL_NOT_PENDING",
  DESIGNER_RUNTIME_CONVERSATION_NOT_READY: "DESIGNER_RUNTIME_CONVERSATION_NOT_READY",
  DESIGNER_RUNTIME_CONVERSATION_BUSY: "DESIGNER_RUNTIME_CONVERSATION_BUSY",
} as const;

export const DesignerNotFoundCodes = {
  DESIGNER_ACTION_PROPOSAL_NOT_FOUND: "DESIGNER_ACTION_PROPOSAL_NOT_FOUND",
  DESIGNER_SESSION_NOT_FOUND: "DESIGNER_SESSION_NOT_FOUND",
} as const;
