export const API_KEYS_ROUTE_BASE_PATH = "/v1/api-keys";

export const ApiKeysBadRequestCodes = {
  INVALID_CREATE_API_KEY_INPUT: "INVALID_CREATE_API_KEY_INPUT",
  INVALID_LIST_API_KEYS_INPUT: "INVALID_LIST_API_KEYS_INPUT",
  INVALID_PAGINATION_CURSOR: "INVALID_PAGINATION_CURSOR",
} as const;
