import { spawn } from "node:child_process";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, resolve } from "node:path";

import { buildDevelopmentTomlConfig, stringifyTomlConfig } from "../config/toml-config.ts";
import { ensureIntegrationRunnerPoolSession } from "./integration-run-id.ts";

type IntegrationVitestProject = {
  projectName: string;
  packageName: string;
  packageDir: string;
  appServicePrewarm: "control-plane" | "data-plane" | "gateway" | "worker" | "none";
};

type SharedInfraPrewarmPlan = {
  postgres: boolean;
  mailpit: boolean;
  seaweedfs: boolean;
  valkey: boolean;
};

type PostgresPrewarmConfig = {
  databaseName?: string;
  username?: string;
  password?: string;
  startupTimeoutMs?: number;
  poolMode?: "session" | "transaction" | "statement";
  defaultPoolSize?: number;
  maxClientConnections?: number;
};

type SharedInfraCoordinator = {
  acquireSharedInfraCoordinatorLease: (input: {
    key: string;
    postgres: PostgresPrewarmConfig | undefined;
    mailpit: boolean;
    seaweedfs: boolean;
    valkey: boolean;
  }) => Promise<unknown>;
  createTestEnvironmentSharedInfraKey: (environment: NodeJS.ProcessEnv) => string;
  stopSharedInfraForTestRun: (runId: string) => Promise<void>;
};

type RunnerServicePools = {
  stopRunnerServicePools: (input: { runId: string; coordinatorDir?: string }) => Promise<void>;
};

type IntegrationTimingFileRecord = {
  type: "integration-file";
  label: string;
  file: string;
  services: string;
  envId: string;
  setupMs: number;
  bodyMs: number;
  teardownMs: number;
  totalMs: number;
  status: "passed" | "failed";
};

type IntegrationTimingSummaryRow = {
  file: string;
  services: string;
  setupMs: number;
  bodyMs: number;
  teardownMs: number;
  totalMs: number;
  tests: number | undefined;
  status: string;
};

type VitestJsonAssertionResult = {
  title?: string;
  fullName?: string;
  ancestorTitles?: string[];
  status?: string;
  durationMs?: number;
};

type VitestJsonResult = {
  name?: string;
  status?: string;
  startTime?: number;
  endTime?: number;
  assertionResults?: VitestJsonAssertionResult[];
};

type VitestJsonReport = {
  testResults?: VitestJsonResult[];
};

type IntegrationTimingTestCaseRow = {
  file: string;
  testName: string;
  durationMs: number;
  status: string;
};

const IntegrationVitestProjects = [
  {
    projectName: "@mistle/control-plane-api",
    packageName: "@mistle/control-plane-api",
    packageDir: "apps/control-plane-api",
    appServicePrewarm: "control-plane",
  },
  {
    projectName: "@mistle/control-plane-worker",
    packageName: "@mistle/control-plane-worker",
    packageDir: "apps/control-plane-worker",
    appServicePrewarm: "worker",
  },
  {
    projectName: "@mistle/dashboard",
    packageName: "@mistle/dashboard",
    packageDir: "apps/dashboard",
    appServicePrewarm: "control-plane",
  },
  {
    projectName: "@mistle/integrations-definitions",
    packageName: "@mistle/integrations-definitions",
    packageDir: "packages/integrations-definitions",
    appServicePrewarm: "none",
  },
  {
    projectName: "@mistle/data-plane-api",
    packageName: "@mistle/data-plane-api",
    packageDir: "apps/data-plane-api",
    appServicePrewarm: "data-plane",
  },
  {
    projectName: "@mistle/data-plane-gateway",
    packageName: "@mistle/data-plane-gateway",
    packageDir: "apps/data-plane-gateway",
    appServicePrewarm: "gateway",
  },
  {
    projectName: "@mistle/data-plane-worker",
    packageName: "@mistle/data-plane-worker",
    packageDir: "apps/data-plane-worker",
    appServicePrewarm: "worker",
  },
] satisfies IntegrationVitestProject[];

const RequiredBuildPackages = [
  "@mistle/control-plane-api",
  "@mistle/control-plane-worker",
  "@mistle/data-plane-api",
  "@mistle/data-plane-gateway",
  "@mistle/data-plane-worker",
  "@mistle/db",
  "@mistle/test-harness",
] as const;

const TimingEnabledValue = "1";
const TimingStartedAtEnv = "MISTLE_TEST_TIMING_STARTED_AT_MS";
const TimingEventsFileEnv = "MISTLE_TEST_TIMING_EVENTS_FILE";
const IntegrationConfigHeader = [
  "# Generated by `pnpm test:integration`.",
  "# This file is scoped to one integration runner session.",
  "",
].join("\n");

function normalizeCliArgs(rawArgs: ReadonlyArray<string>): string[] {
  if (rawArgs[0] === "--") {
    return rawArgs.slice(1);
  }

  return [...rawArgs];
}

function parseProjectFilters(args: ReadonlyArray<string>): string[] {
  const projectFilters: string[] = [];

  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index];
    if (argument === undefined) {
      throw new Error(`Expected an argument at index ${String(index)}.`);
    }
    if (argument === "--project") {
      const projectName = args[index + 1];
      if (projectName === undefined || projectName.length === 0) {
        throw new Error("Expected a project name after --project.");
      }
      projectFilters.push(projectName);
      index += 1;
      continue;
    }

    const projectPrefix = "--project=";
    if (argument.startsWith(projectPrefix)) {
      const projectName = argument.slice(projectPrefix.length);
      if (projectName.length === 0) {
        throw new Error("Expected a non-empty project name in --project=<name>.");
      }
      projectFilters.push(projectName);
    }
  }

  return projectFilters;
}

function parseIntegrationFileFilters(args: ReadonlyArray<string>): string[] {
  const fileFilters: string[] = [];

  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index];
    if (argument === undefined) {
      throw new Error(`Expected an argument at index ${String(index)}.`);
    }
    if (argument === "--project") {
      index += 1;
      continue;
    }
    if (argument.startsWith("--")) {
      continue;
    }
    if (argument.includes("integration/") || argument.endsWith(".ts")) {
      fileFilters.push(argument);
    }
  }

  return fileFilters;
}

function resolveSelectedProjects(
  projectFilters: ReadonlyArray<string>,
): IntegrationVitestProject[] {
  if (projectFilters.length === 0) {
    return [...IntegrationVitestProjects];
  }

  const selectedProjects: IntegrationVitestProject[] = [];

  for (const projectFilter of projectFilters) {
    const project = IntegrationVitestProjects.find(
      (candidate) => candidate.projectName === projectFilter,
    );
    if (project === undefined) {
      throw new Error(
        `Unknown integration Vitest project '${projectFilter}'. Expected one of: ${IntegrationVitestProjects.map((candidate) => candidate.projectName).join(", ")}.`,
      );
    }
    if (!selectedProjects.includes(project)) {
      selectedProjects.push(project);
    }
  }

  return selectedProjects;
}

function formatDuration(milliseconds: number): string {
  return `${(milliseconds / 1000).toFixed(2)}s`;
}

async function listIntegrationTestFiles(directory: string): Promise<string[]> {
  let entries;
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch (error) {
    if (isErrnoException(error) && error.code === "ENOENT") {
      return [];
    }
    throw error;
  }

  const files: string[] = [];
  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listIntegrationTestFiles(path)));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(".test.ts")) {
      files.push(path);
    }
  }

  return files;
}

function isErrnoException(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}

function isTimingEnabled(environment: NodeJS.ProcessEnv): boolean {
  return environment["MISTLE_TEST_TIMING"] === TimingEnabledValue;
}

function hasCliOption(args: ReadonlyArray<string>, option: string): boolean {
  const optionPrefix = `${option}=`;
  const dottedOptionPrefix = `${option}.`;
  return args.some(
    (argument) =>
      argument === option ||
      argument.startsWith(optionPrefix) ||
      argument.startsWith(dottedOptionPrefix),
  );
}

function createTimingArtifacts(input: {
  runnerPoolSession: { coordinatorDir: string };
  environment: NodeJS.ProcessEnv;
}): { eventsFile: string; vitestJsonFile: string } | undefined {
  if (!isTimingEnabled(input.environment)) {
    return undefined;
  }

  const timingDir = join(input.runnerPoolSession.coordinatorDir, "timing");
  const artifacts = {
    eventsFile:
      input.environment[TimingEventsFileEnv] ?? join(timingDir, "integration-events.jsonl"),
    vitestJsonFile: join(timingDir, "vitest-results.json"),
  };
  input.environment[TimingEventsFileEnv] = artifacts.eventsFile;

  return artifacts;
}

async function initializeTimingArtifacts(
  artifacts: { eventsFile: string; vitestJsonFile: string } | undefined,
): Promise<void> {
  if (artifacts === undefined) {
    return;
  }

  await mkdir(dirname(artifacts.eventsFile), { recursive: true });
  await writeFile(artifacts.eventsFile, "", "utf8");
  await mkdir(dirname(artifacts.vitestJsonFile), { recursive: true });
}

function addTimingVitestReporter(input: {
  cliArgs: ReadonlyArray<string>;
  vitestJsonFile: string | undefined;
}): string[] {
  if (
    input.vitestJsonFile === undefined ||
    hasCliOption(input.cliArgs, "--reporter") ||
    hasCliOption(input.cliArgs, "--reporters") ||
    hasCliOption(input.cliArgs, "--outputFile")
  ) {
    return [...input.cliArgs];
  }

  return [
    ...input.cliArgs,
    "--reporter=default",
    "--reporter=json",
    "--outputFile",
    input.vitestJsonFile,
  ];
}

function readStringProperty(input: object, key: string): string | undefined {
  const value = Reflect.get(input, key);
  return typeof value === "string" ? value : undefined;
}

function readNumberProperty(input: object, key: string): number | undefined {
  const value = Reflect.get(input, key);
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

function readStringArrayProperty(input: object, key: string): string[] | undefined {
  const value = Reflect.get(input, key);
  return Array.isArray(value) && value.every((item) => typeof item === "string")
    ? value
    : undefined;
}

function parseIntegrationTimingFileRecord(input: unknown): IntegrationTimingFileRecord | undefined {
  if (typeof input !== "object" || input === null) {
    return undefined;
  }

  const type = readStringProperty(input, "type");
  const status = readStringProperty(input, "status");
  const label = readStringProperty(input, "label");
  const file = readStringProperty(input, "file");
  const services = readStringProperty(input, "services");
  const envId = readStringProperty(input, "envId");
  const setupMs = readNumberProperty(input, "setupMs");
  const bodyMs = readNumberProperty(input, "bodyMs");
  const teardownMs = readNumberProperty(input, "teardownMs");
  const totalMs = readNumberProperty(input, "totalMs");

  if (
    type !== "integration-file" ||
    (status !== "passed" && status !== "failed") ||
    label === undefined ||
    file === undefined ||
    services === undefined ||
    envId === undefined ||
    setupMs === undefined ||
    bodyMs === undefined ||
    teardownMs === undefined ||
    totalMs === undefined
  ) {
    return undefined;
  }

  return {
    type,
    label,
    file,
    services,
    envId,
    setupMs,
    bodyMs,
    teardownMs,
    totalMs,
    status,
  };
}

function parseVitestJsonAssertionResult(input: unknown): VitestJsonAssertionResult | undefined {
  if (typeof input !== "object" || input === null) {
    return undefined;
  }

  const title = readStringProperty(input, "title");
  const fullName = readStringProperty(input, "fullName");
  const ancestorTitles = readStringArrayProperty(input, "ancestorTitles");
  const status = readStringProperty(input, "status");
  const durationMs = readNumberProperty(input, "duration");

  if (
    title === undefined &&
    fullName === undefined &&
    ancestorTitles === undefined &&
    status === undefined &&
    durationMs === undefined
  ) {
    return undefined;
  }

  const result: VitestJsonAssertionResult = {};
  if (title !== undefined) {
    result.title = title;
  }
  if (fullName !== undefined) {
    result.fullName = fullName;
  }
  if (ancestorTitles !== undefined) {
    result.ancestorTitles = ancestorTitles;
  }
  if (status !== undefined) {
    result.status = status;
  }
  if (durationMs !== undefined) {
    result.durationMs = durationMs;
  }

  return result;
}

function parseVitestJsonResult(input: unknown): VitestJsonResult | undefined {
  if (typeof input !== "object" || input === null) {
    return undefined;
  }

  const assertionResults = Reflect.get(input, "assertionResults");
  const result: VitestJsonResult = {};
  const name = readStringProperty(input, "name");
  const status = readStringProperty(input, "status");
  const startTime = readNumberProperty(input, "startTime");
  const endTime = readNumberProperty(input, "endTime");

  if (name !== undefined) {
    result.name = name;
  }
  if (status !== undefined) {
    result.status = status;
  }
  if (startTime !== undefined) {
    result.startTime = startTime;
  }
  if (endTime !== undefined) {
    result.endTime = endTime;
  }
  if (Array.isArray(assertionResults)) {
    result.assertionResults = assertionResults
      .map((assertionResult) => parseVitestJsonAssertionResult(assertionResult))
      .filter((assertionResult) => assertionResult !== undefined);
  }

  return result;
}

function parseVitestJsonReport(input: unknown): VitestJsonReport {
  if (typeof input !== "object" || input === null) {
    return {};
  }

  const testResults = Reflect.get(input, "testResults");
  if (!Array.isArray(testResults)) {
    return {};
  }

  return {
    testResults: testResults
      .map((result) => parseVitestJsonResult(result))
      .filter((result) => result !== undefined),
  };
}

async function readIntegrationTimingRecords(
  eventsFile: string | undefined,
): Promise<IntegrationTimingFileRecord[]> {
  if (eventsFile === undefined) {
    return [];
  }

  let contents;
  try {
    contents = await readFile(eventsFile, "utf8");
  } catch (error) {
    if (isErrnoException(error) && error.code === "ENOENT") {
      return [];
    }
    throw error;
  }

  return contents
    .split("\n")
    .filter((line) => line.length > 0)
    .map((line) => parseIntegrationTimingFileRecord(JSON.parse(line)))
    .filter((record) => record !== undefined);
}

async function readVitestJsonResults(
  vitestJsonFile: string | undefined,
): Promise<Map<string, VitestJsonResult>> {
  const results = new Map<string, VitestJsonResult>();
  if (vitestJsonFile === undefined) {
    return results;
  }

  let contents;
  try {
    contents = await readFile(vitestJsonFile, "utf8");
  } catch (error) {
    if (isErrnoException(error) && error.code === "ENOENT") {
      return results;
    }
    throw error;
  }

  const report = parseVitestJsonReport(JSON.parse(contents));
  for (const result of report.testResults ?? []) {
    if (result.name === undefined) {
      continue;
    }
    results.set(normalizeReportFile(result.name), result);
  }

  return results;
}

function normalizeReportFile(file: string): string {
  const absolutePath = isAbsolute(file) ? file : resolve(process.cwd(), file);
  const relativePath = absolutePath.startsWith(`${process.cwd()}/`)
    ? absolutePath.slice(process.cwd().length + 1)
    : absolutePath;

  return relativePath.replaceAll("\\", "/");
}

function summarizeIntegrationTiming(input: {
  records: ReadonlyArray<IntegrationTimingFileRecord>;
  vitestResults: ReadonlyMap<string, VitestJsonResult>;
}): IntegrationTimingSummaryRow[] {
  const rows = new Map<string, IntegrationTimingSummaryRow>();

  for (const record of input.records) {
    const file = normalizeReportFile(record.file);
    const existing = rows.get(file);
    if (existing === undefined) {
      rows.set(file, {
        file,
        services: record.services,
        setupMs: record.setupMs,
        bodyMs: record.bodyMs,
        teardownMs: record.teardownMs,
        totalMs: record.totalMs,
        tests: undefined,
        status: record.status,
      });
      continue;
    }

    existing.setupMs += record.setupMs;
    existing.bodyMs += record.bodyMs;
    existing.teardownMs += record.teardownMs;
    existing.totalMs += record.totalMs;
    existing.status =
      existing.status === "failed" || record.status === "failed" ? "failed" : "passed";
    if (!existing.services.split(" | ").includes(record.services)) {
      existing.services = `${existing.services} | ${record.services}`;
    }
  }

  for (const [file, row] of rows.entries()) {
    const vitestResult = input.vitestResults.get(file);
    if (vitestResult === undefined) {
      continue;
    }
    row.tests = vitestResult.assertionResults?.length;
    row.status = vitestResult.status ?? row.status;
    if (vitestResult.startTime !== undefined && vitestResult.endTime !== undefined) {
      const vitestDurationMs = vitestResult.endTime - vitestResult.startTime;
      if (vitestDurationMs > 0) {
        row.totalMs = vitestDurationMs;
      }
    }
  }

  return [...rows.values()];
}

function summarizeIntegrationTestCaseTiming(input: {
  vitestResults: ReadonlyMap<string, VitestJsonResult>;
}): IntegrationTimingTestCaseRow[] {
  const rows: IntegrationTimingTestCaseRow[] = [];

  for (const [file, result] of input.vitestResults.entries()) {
    for (const assertionResult of result.assertionResults ?? []) {
      if (assertionResult.durationMs === undefined) {
        continue;
      }

      const testName =
        assertionResult.fullName ??
        [...(assertionResult.ancestorTitles ?? []), assertionResult.title ?? "(unnamed test)"].join(
          " > ",
        );
      rows.push({
        file,
        testName,
        durationMs: assertionResult.durationMs,
        status: assertionResult.status ?? result.status ?? "unknown",
      });
    }
  }

  return rows;
}

function truncateMiddle(value: string, width: number): string {
  if (value.length <= width) {
    return value.padEnd(width);
  }
  if (width <= 1) {
    return value.slice(0, width);
  }

  return `${value.slice(0, width - 1)}…`;
}

function formatReportCount(count: number | undefined): string {
  return count === undefined ? "-" : String(count);
}

function writeTimingTable(input: {
  title: string;
  rows: ReadonlyArray<IntegrationTimingSummaryRow>;
  sortBy: keyof Pick<IntegrationTimingSummaryRow, "totalMs" | "bodyMs" | "setupMs" | "teardownMs">;
}): void {
  const rows = [...input.rows].sort((left, right) => right[input.sortBy] - left[input.sortBy]);
  if (rows.length === 0) {
    return;
  }

  console.info(`\n[integration] ${input.title}`);
  console.info(
    [
      "file".padEnd(72),
      "total".padStart(7),
      "setup".padStart(7),
      "body".padStart(7),
      "teardown".padStart(9),
      "tests".padStart(5),
      "status".padEnd(7),
      "services",
    ].join("  "),
  );
  for (const row of rows.slice(0, 15)) {
    console.info(
      [
        truncateMiddle(row.file, 72),
        formatDuration(row.totalMs).padStart(7),
        formatDuration(row.setupMs).padStart(7),
        formatDuration(row.bodyMs).padStart(7),
        formatDuration(row.teardownMs).padStart(9),
        formatReportCount(row.tests).padStart(5),
        row.status.padEnd(7),
        row.services,
      ].join("  "),
    );
  }
}

function writeTestCaseTimingTable(rows: ReadonlyArray<IntegrationTimingTestCaseRow>): void {
  const sortedRows = [...rows].sort((left, right) => right.durationMs - left.durationMs);
  if (sortedRows.length === 0) {
    return;
  }

  console.info("\n[integration] slowest integration test cases by wall time");
  console.info(["file".padEnd(58), "duration".padStart(8), "status".padEnd(7), "test"].join("  "));
  for (const row of sortedRows.slice(0, 15)) {
    console.info(
      [
        truncateMiddle(row.file, 58),
        formatDuration(row.durationMs).padStart(8),
        row.status.padEnd(7),
        truncateMiddle(row.testName, 100),
      ].join("  "),
    );
  }
}

async function writeIntegrationTimingSummary(input: {
  eventsFile: string | undefined;
  vitestJsonFile: string | undefined;
}): Promise<void> {
  const records = await readIntegrationTimingRecords(input.eventsFile);
  if (records.length === 0) {
    return;
  }

  const vitestResults = await readVitestJsonResults(input.vitestJsonFile);
  const rows = summarizeIntegrationTiming({
    records,
    vitestResults,
  });

  writeTimingTable({
    title: "slowest integration files by wall time",
    rows,
    sortBy: "totalMs",
  });
  writeTestCaseTimingTable(
    summarizeIntegrationTestCaseTiming({
      vitestResults,
    }),
  );
  writeTimingTable({
    title: "largest aggregate integration body targets",
    rows,
    sortBy: "bodyMs",
  });
}

async function readExtraInfraPrewarmPlanFromTests(input: {
  selectedProjects: ReadonlyArray<IntegrationVitestProject>;
  fileFilters: ReadonlyArray<string>;
}): Promise<Pick<SharedInfraPrewarmPlan, "mailpit" | "seaweedfs">> {
  const files =
    input.fileFilters.length === 0
      ? (
          await Promise.all(
            input.selectedProjects.map((project) =>
              listIntegrationTestFiles(resolve(process.cwd(), project.packageDir, "integration")),
            ),
          )
        ).flat()
      : input.fileFilters.map((fileFilter) =>
          isAbsolute(fileFilter) ? fileFilter : resolve(process.cwd(), fileFilter),
        );

  const plan = {
    mailpit: false,
    seaweedfs: false,
  };

  await Promise.all(
    files.map(async (file) => {
      let contents;
      try {
        contents = await readFile(file, "utf8");
      } catch (error) {
        if (isErrnoException(error) && error.code === "ENOENT") {
          return;
        }
        throw error;
      }

      if (/extraInfra\s*:\s*\[[^\]]*["']mailpit["']/s.test(contents)) {
        plan.mailpit = true;
      }
      if (/extraInfra\s*:\s*\[[^\]]*["']seaweedfs["']/s.test(contents)) {
        plan.seaweedfs = true;
      }
    }),
  );

  return plan;
}

async function resolveSharedInfraPrewarmPlan(
  selectedProjects: ReadonlyArray<IntegrationVitestProject>,
  fileFilters: ReadonlyArray<string>,
): Promise<SharedInfraPrewarmPlan> {
  const plan: SharedInfraPrewarmPlan = {
    postgres: false,
    mailpit: false,
    seaweedfs: false,
    valkey: false,
  };

  for (const project of selectedProjects) {
    switch (project.appServicePrewarm) {
      case "control-plane":
      case "data-plane":
      case "worker":
        plan.postgres = true;
        break;
      case "gateway":
        plan.postgres = true;
        plan.valkey = true;
        break;
      case "none":
        break;
    }
  }

  const extraInfraPlan = await readExtraInfraPrewarmPlanFromTests({
    selectedProjects,
    fileFilters,
  });
  plan.mailpit = extraInfraPlan.mailpit;
  plan.seaweedfs = extraInfraPlan.seaweedfs;

  return plan;
}

function describeSharedInfraPrewarmPlan(plan: SharedInfraPrewarmPlan): string {
  const services: string[] = [];
  if (plan.postgres) {
    services.push("postgres");
  }
  if (plan.mailpit) {
    services.push("mailpit");
  }
  if (plan.seaweedfs) {
    services.push("seaweedfs");
  }
  if (plan.valkey) {
    services.push("valkey");
  }

  return services.length === 0 ? "none" : services.join(", ");
}

async function prewarmSharedInfra(
  selectedProjects: ReadonlyArray<IntegrationVitestProject>,
  fileFilters: ReadonlyArray<string>,
  coordinator: SharedInfraCoordinator,
): Promise<void> {
  const plan = await resolveSharedInfraPrewarmPlan(selectedProjects, fileFilters);
  if (!plan.postgres && !plan.mailpit && !plan.seaweedfs && !plan.valkey) {
    writeIntegrationTimingEvent("runner shared infra prewarm skipped", "none required");
    return;
  }

  const startedAt = Date.now();
  console.info(`[integration] prewarming shared infra: ${describeSharedInfraPrewarmPlan(plan)}.`);
  await coordinator.acquireSharedInfraCoordinatorLease({
    key: coordinator.createTestEnvironmentSharedInfraKey(process.env),
    postgres: plan.postgres ? {} : undefined,
    mailpit: plan.mailpit,
    seaweedfs: plan.seaweedfs,
    valkey: plan.valkey,
  });
  console.info(
    `[integration] shared infra prewarm completed in ${formatDuration(Date.now() - startedAt)}.`,
  );
}

function markIntegrationTimingStart(environment: NodeJS.ProcessEnv): void {
  if (environment["MISTLE_TEST_TIMING"] !== TimingEnabledValue) {
    return;
  }

  if (environment[TimingStartedAtEnv] === undefined) {
    environment[TimingStartedAtEnv] = String(Date.now());
  }
}

function writeIntegrationTimingEvent(event: string, details: string): void {
  if (process.env["MISTLE_TEST_TIMING"] !== TimingEnabledValue) {
    return;
  }

  process.stderr.write(
    `[integration] ${formatTimingOffset()} pid=${String(process.pid)} worker=unknown ${event}: ${details}.\n`,
  );
}

async function ensureIntegrationConfigPath(input: {
  runnerPoolSession: { coordinatorDir: string };
  environment: NodeJS.ProcessEnv;
}): Promise<void> {
  const existingConfigPath = input.environment["MISTLE_CONFIG_PATH"];
  if (existingConfigPath !== undefined && existingConfigPath.length > 0) {
    console.info(`[integration] using config from MISTLE_CONFIG_PATH: ${existingConfigPath}.`);
    return;
  }

  const configPath = join(input.runnerPoolSession.coordinatorDir, "config", "config.toml");
  await mkdir(dirname(configPath), { recursive: true });
  await writeFile(
    configPath,
    stringifyTomlConfig({
      header: IntegrationConfigHeader,
      configRoot: buildDevelopmentTomlConfig(),
    }),
    "utf8",
  );
  input.environment["MISTLE_CONFIG_PATH"] = configPath;
  console.info(`[integration] generated runner config: ${configPath}.`);
}

function formatTimingOffset(): string {
  const startedAtValue = process.env[TimingStartedAtEnv];
  if (startedAtValue === undefined || startedAtValue.length === 0) {
    return "t=unknown";
  }

  const startedAt = Number(startedAtValue);
  if (!Number.isFinite(startedAt)) {
    return "t=unknown";
  }

  return `t=+${formatDuration(Date.now() - startedAt)}`;
}

async function runCommand(command: string, args: ReadonlyArray<string>): Promise<void> {
  await new Promise<void>((resolvePromise, reject) => {
    writeIntegrationTimingEvent("runner command spawn", `${command} ${args.join(" ")}`);
    const child = spawn(command, args, {
      cwd: process.cwd(),
      env: process.env,
      stdio: "inherit",
    });

    writeIntegrationTimingEvent(
      "runner command spawned",
      `${command} pid=${child.pid === undefined ? "unknown" : String(child.pid)}`,
    );

    child.on("error", reject);
    child.on("exit", (code, signal) => {
      writeIntegrationTimingEvent(
        "runner command exited",
        `${command} code=${String(code)} signal=${signal === null ? "none" : signal}`,
      );
      if (code === 0) {
        resolvePromise();
        return;
      }

      reject(
        new Error(
          `${command} ${args.join(" ")} exited with code ${String(code)}${signal === null ? "" : ` and signal ${signal}`}.`,
        ),
      );
    });
  });
}

async function runTimedCommand(input: {
  label: string;
  command: string;
  args: ReadonlyArray<string>;
}): Promise<void> {
  const startedAt = Date.now();
  await runCommand(input.command, input.args);
  console.info(
    `[integration] ${input.label} completed in ${formatDuration(Date.now() - startedAt)}.`,
  );
}

async function loadSharedInfraCoordinator(): Promise<SharedInfraCoordinator> {
  // The runner must build workspace packages before loading harness internals.
  return await import("../../packages/test-harness/src/services/shared-infra-coordinator.ts");
}

async function loadRunnerServicePools(): Promise<RunnerServicePools> {
  // The runner must build workspace packages before loading harness internals.
  return await import("../../packages/test-harness/src/environment/runner-service-pool.ts");
}

async function main(): Promise<void> {
  const startedAt = Date.now();
  markIntegrationTimingStart(process.env);
  const runnerPoolSession = ensureIntegrationRunnerPoolSession(process.env);
  const cliArgs = normalizeCliArgs(process.argv.slice(2));
  const projectFilters = parseProjectFilters(cliArgs);
  const fileFilters = parseIntegrationFileFilters(cliArgs);
  const selectedProjects = resolveSelectedProjects(projectFilters);
  const selectedBuildPackages = new Set<string>(RequiredBuildPackages);
  const timingArtifacts = createTimingArtifacts({
    runnerPoolSession,
    environment: process.env,
  });
  await initializeTimingArtifacts(timingArtifacts);
  const vitestCliArgs = addTimingVitestReporter({
    cliArgs,
    vitestJsonFile: timingArtifacts?.vitestJsonFile,
  });

  for (const project of selectedProjects) {
    selectedBuildPackages.add(project.packageName);
  }

  console.info(`Using integration run id ${runnerPoolSession.runId}.`);
  await ensureIntegrationConfigPath({
    runnerPoolSession,
    environment: process.env,
  });
  writeIntegrationTimingEvent(
    "runner selected projects",
    selectedProjects.map((project) => project.projectName).join(", "),
  );

  await runTimedCommand({
    label: "build",
    command: "pnpm",
    args: [
      "turbo",
      "run",
      "build",
      ...Array.from(selectedBuildPackages).flatMap((packageName) => [
        "--filter",
        `${packageName}...`,
      ]),
    ],
  });

  const sharedInfraCoordinator = await loadSharedInfraCoordinator();
  const runnerServicePools = await loadRunnerServicePools();

  try {
    await prewarmSharedInfra(selectedProjects, fileFilters, sharedInfraCoordinator);
    try {
      await runTimedCommand({
        label: "vitest",
        command: "pnpm",
        args: ["exec", "vitest", "run", "-c", "vitest.integration.root.ts", ...vitestCliArgs],
      });
    } finally {
      await writeIntegrationTimingSummary({
        eventsFile: timingArtifacts?.eventsFile,
        vitestJsonFile: timingArtifacts?.vitestJsonFile,
      });
    }
  } finally {
    const cleanupStartedAt = Date.now();
    await runnerServicePools.stopRunnerServicePools({
      runId: runnerPoolSession.runId,
      coordinatorDir: runnerPoolSession.coordinatorDir,
    });
    await sharedInfraCoordinator.stopSharedInfraForTestRun(runnerPoolSession.runId);
    console.info(
      `[integration] pooled service/infra cleanup completed in ${formatDuration(Date.now() - cleanupStartedAt)}.`,
    );
  }

  console.info(`[integration] total completed in ${formatDuration(Date.now() - startedAt)}.`);
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? (error.stack ?? error.message) : String(error);
  console.error(message);
  process.exitCode = 1;
});
