import { spawn } from "node:child_process";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, resolve } from "node:path";

import { buildDevelopmentTomlConfig, stringifyTomlConfig } from "../config/toml-config.ts";
import { ensureIntegrationRunnerPoolSession } from "./integration-run-id.ts";

type IntegrationVitestProject = {
  projectName: string;
  packageName: string;
  packageDir: string;
  appServicePrewarm: "control-plane" | "data-plane" | "gateway" | "worker" | "none";
};

type SharedInfraPrewarmPlan = {
  postgres: boolean;
  mailpit: boolean;
  seaweedfs: boolean;
  valkey: boolean;
};

type PostgresPrewarmConfig = {
  databaseName?: string;
  username?: string;
  password?: string;
  startupTimeoutMs?: number;
  poolMode?: "session" | "transaction" | "statement";
  defaultPoolSize?: number;
  maxClientConnections?: number;
};

type SharedInfraCoordinator = {
  acquireSharedInfraCoordinatorLease: (input: {
    key: string;
    postgres: PostgresPrewarmConfig | undefined;
    mailpit: boolean;
    seaweedfs: boolean;
    valkey: boolean;
  }) => Promise<unknown>;
  createTestEnvironmentSharedInfraKey: (environment: NodeJS.ProcessEnv) => string;
  stopSharedInfraForTestRun: (runId: string) => Promise<void>;
};

type RunnerServicePools = {
  stopRunnerServicePools: (input: { runId: string; coordinatorDir?: string }) => Promise<void>;
};

const IntegrationVitestProjects = [
  {
    projectName: "@mistle/control-plane-api",
    packageName: "@mistle/control-plane-api",
    packageDir: "apps/control-plane-api",
    appServicePrewarm: "control-plane",
  },
  {
    projectName: "@mistle/control-plane-worker",
    packageName: "@mistle/control-plane-worker",
    packageDir: "apps/control-plane-worker",
    appServicePrewarm: "worker",
  },
  {
    projectName: "@mistle/dashboard",
    packageName: "@mistle/dashboard",
    packageDir: "apps/dashboard",
    appServicePrewarm: "control-plane",
  },
  {
    projectName: "@mistle/integrations-definitions",
    packageName: "@mistle/integrations-definitions",
    packageDir: "packages/integrations-definitions",
    appServicePrewarm: "none",
  },
  {
    projectName: "@mistle/data-plane-api",
    packageName: "@mistle/data-plane-api",
    packageDir: "apps/data-plane-api",
    appServicePrewarm: "data-plane",
  },
  {
    projectName: "@mistle/data-plane-gateway",
    packageName: "@mistle/data-plane-gateway",
    packageDir: "apps/data-plane-gateway",
    appServicePrewarm: "gateway",
  },
  {
    projectName: "@mistle/data-plane-worker",
    packageName: "@mistle/data-plane-worker",
    packageDir: "apps/data-plane-worker",
    appServicePrewarm: "worker",
  },
] satisfies IntegrationVitestProject[];

const RequiredBuildPackages = [
  "@mistle/control-plane-api",
  "@mistle/control-plane-worker",
  "@mistle/data-plane-api",
  "@mistle/data-plane-gateway",
  "@mistle/data-plane-worker",
  "@mistle/db",
  "@mistle/test-harness",
] as const;

const TimingEnabledValue = "1";
const TimingStartedAtEnv = "MISTLE_TEST_TIMING_STARTED_AT_MS";
const IntegrationConfigHeader = [
  "# Generated by `pnpm test:integration`.",
  "# This file is scoped to one integration runner session.",
  "",
].join("\n");

function normalizeCliArgs(rawArgs: ReadonlyArray<string>): string[] {
  if (rawArgs[0] === "--") {
    return rawArgs.slice(1);
  }

  return [...rawArgs];
}

function parseProjectFilters(args: ReadonlyArray<string>): string[] {
  const projectFilters: string[] = [];

  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index];
    if (argument === undefined) {
      throw new Error(`Expected an argument at index ${String(index)}.`);
    }
    if (argument === "--project") {
      const projectName = args[index + 1];
      if (projectName === undefined || projectName.length === 0) {
        throw new Error("Expected a project name after --project.");
      }
      projectFilters.push(projectName);
      index += 1;
      continue;
    }

    const projectPrefix = "--project=";
    if (argument.startsWith(projectPrefix)) {
      const projectName = argument.slice(projectPrefix.length);
      if (projectName.length === 0) {
        throw new Error("Expected a non-empty project name in --project=<name>.");
      }
      projectFilters.push(projectName);
    }
  }

  return projectFilters;
}

function parseIntegrationFileFilters(args: ReadonlyArray<string>): string[] {
  const fileFilters: string[] = [];

  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index];
    if (argument === undefined) {
      throw new Error(`Expected an argument at index ${String(index)}.`);
    }
    if (argument === "--project") {
      index += 1;
      continue;
    }
    if (argument.startsWith("--")) {
      continue;
    }
    if (argument.includes("integration/") || argument.endsWith(".ts")) {
      fileFilters.push(argument);
    }
  }

  return fileFilters;
}

function resolveSelectedProjects(
  projectFilters: ReadonlyArray<string>,
): IntegrationVitestProject[] {
  if (projectFilters.length === 0) {
    return [...IntegrationVitestProjects];
  }

  const selectedProjects: IntegrationVitestProject[] = [];

  for (const projectFilter of projectFilters) {
    const project = IntegrationVitestProjects.find(
      (candidate) => candidate.projectName === projectFilter,
    );
    if (project === undefined) {
      throw new Error(
        `Unknown integration Vitest project '${projectFilter}'. Expected one of: ${IntegrationVitestProjects.map((candidate) => candidate.projectName).join(", ")}.`,
      );
    }
    if (!selectedProjects.includes(project)) {
      selectedProjects.push(project);
    }
  }

  return selectedProjects;
}

function formatDuration(milliseconds: number): string {
  return `${(milliseconds / 1000).toFixed(2)}s`;
}

async function listIntegrationTestFiles(directory: string): Promise<string[]> {
  let entries;
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch (error) {
    if (isErrnoException(error) && error.code === "ENOENT") {
      return [];
    }
    throw error;
  }

  const files: string[] = [];
  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listIntegrationTestFiles(path)));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(".test.ts")) {
      files.push(path);
    }
  }

  return files;
}

function isErrnoException(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}

async function readExtraInfraPrewarmPlanFromTests(input: {
  selectedProjects: ReadonlyArray<IntegrationVitestProject>;
  fileFilters: ReadonlyArray<string>;
}): Promise<Pick<SharedInfraPrewarmPlan, "mailpit" | "seaweedfs">> {
  const files =
    input.fileFilters.length === 0
      ? (
          await Promise.all(
            input.selectedProjects.map((project) =>
              listIntegrationTestFiles(resolve(process.cwd(), project.packageDir, "integration")),
            ),
          )
        ).flat()
      : input.fileFilters.map((fileFilter) =>
          isAbsolute(fileFilter) ? fileFilter : resolve(process.cwd(), fileFilter),
        );

  const plan = {
    mailpit: false,
    seaweedfs: false,
  };

  await Promise.all(
    files.map(async (file) => {
      let contents;
      try {
        contents = await readFile(file, "utf8");
      } catch (error) {
        if (isErrnoException(error) && error.code === "ENOENT") {
          return;
        }
        throw error;
      }

      if (/extraInfra\s*:\s*\[[^\]]*["']mailpit["']/s.test(contents)) {
        plan.mailpit = true;
      }
      if (/extraInfra\s*:\s*\[[^\]]*["']seaweedfs["']/s.test(contents)) {
        plan.seaweedfs = true;
      }
    }),
  );

  return plan;
}

async function resolveSharedInfraPrewarmPlan(
  selectedProjects: ReadonlyArray<IntegrationVitestProject>,
  fileFilters: ReadonlyArray<string>,
): Promise<SharedInfraPrewarmPlan> {
  const plan: SharedInfraPrewarmPlan = {
    postgres: false,
    mailpit: false,
    seaweedfs: false,
    valkey: false,
  };

  for (const project of selectedProjects) {
    switch (project.appServicePrewarm) {
      case "control-plane":
      case "data-plane":
      case "worker":
        plan.postgres = true;
        break;
      case "gateway":
        plan.postgres = true;
        plan.valkey = true;
        break;
      case "none":
        break;
    }
  }

  const extraInfraPlan = await readExtraInfraPrewarmPlanFromTests({
    selectedProjects,
    fileFilters,
  });
  plan.mailpit = extraInfraPlan.mailpit;
  plan.seaweedfs = extraInfraPlan.seaweedfs;

  return plan;
}

function describeSharedInfraPrewarmPlan(plan: SharedInfraPrewarmPlan): string {
  const services: string[] = [];
  if (plan.postgres) {
    services.push("postgres");
  }
  if (plan.mailpit) {
    services.push("mailpit");
  }
  if (plan.seaweedfs) {
    services.push("seaweedfs");
  }
  if (plan.valkey) {
    services.push("valkey");
  }

  return services.length === 0 ? "none" : services.join(", ");
}

async function prewarmSharedInfra(
  selectedProjects: ReadonlyArray<IntegrationVitestProject>,
  fileFilters: ReadonlyArray<string>,
  coordinator: SharedInfraCoordinator,
): Promise<void> {
  const plan = await resolveSharedInfraPrewarmPlan(selectedProjects, fileFilters);
  if (!plan.postgres && !plan.mailpit && !plan.seaweedfs && !plan.valkey) {
    writeIntegrationTimingEvent("runner shared infra prewarm skipped", "none required");
    return;
  }

  const startedAt = Date.now();
  console.info(`[integration] prewarming shared infra: ${describeSharedInfraPrewarmPlan(plan)}.`);
  await coordinator.acquireSharedInfraCoordinatorLease({
    key: coordinator.createTestEnvironmentSharedInfraKey(process.env),
    postgres: plan.postgres ? {} : undefined,
    mailpit: plan.mailpit,
    seaweedfs: plan.seaweedfs,
    valkey: plan.valkey,
  });
  console.info(
    `[integration] shared infra prewarm completed in ${formatDuration(Date.now() - startedAt)}.`,
  );
}

function markIntegrationTimingStart(environment: NodeJS.ProcessEnv): void {
  if (environment["MISTLE_TEST_TIMING"] !== TimingEnabledValue) {
    return;
  }

  if (environment[TimingStartedAtEnv] === undefined) {
    environment[TimingStartedAtEnv] = String(Date.now());
  }
}

function writeIntegrationTimingEvent(event: string, details: string): void {
  if (process.env["MISTLE_TEST_TIMING"] !== TimingEnabledValue) {
    return;
  }

  process.stderr.write(
    `[integration] ${formatTimingOffset()} pid=${String(process.pid)} worker=unknown ${event}: ${details}.\n`,
  );
}

async function ensureIntegrationConfigPath(input: {
  runnerPoolSession: { coordinatorDir: string };
  environment: NodeJS.ProcessEnv;
}): Promise<void> {
  const existingConfigPath = input.environment["MISTLE_CONFIG_PATH"];
  if (existingConfigPath !== undefined && existingConfigPath.length > 0) {
    console.info(`[integration] using config from MISTLE_CONFIG_PATH: ${existingConfigPath}.`);
    return;
  }

  const configPath = join(input.runnerPoolSession.coordinatorDir, "config", "config.toml");
  await mkdir(dirname(configPath), { recursive: true });
  await writeFile(
    configPath,
    stringifyTomlConfig({
      header: IntegrationConfigHeader,
      configRoot: buildDevelopmentTomlConfig(),
    }),
    "utf8",
  );
  input.environment["MISTLE_CONFIG_PATH"] = configPath;
  console.info(`[integration] generated runner config: ${configPath}.`);
}

function formatTimingOffset(): string {
  const startedAtValue = process.env[TimingStartedAtEnv];
  if (startedAtValue === undefined || startedAtValue.length === 0) {
    return "t=unknown";
  }

  const startedAt = Number(startedAtValue);
  if (!Number.isFinite(startedAt)) {
    return "t=unknown";
  }

  return `t=+${formatDuration(Date.now() - startedAt)}`;
}

async function runCommand(command: string, args: ReadonlyArray<string>): Promise<void> {
  await new Promise<void>((resolvePromise, reject) => {
    writeIntegrationTimingEvent("runner command spawn", `${command} ${args.join(" ")}`);
    const child = spawn(command, args, {
      cwd: process.cwd(),
      env: process.env,
      stdio: "inherit",
    });

    writeIntegrationTimingEvent(
      "runner command spawned",
      `${command} pid=${child.pid === undefined ? "unknown" : String(child.pid)}`,
    );

    child.on("error", reject);
    child.on("exit", (code, signal) => {
      writeIntegrationTimingEvent(
        "runner command exited",
        `${command} code=${String(code)} signal=${signal === null ? "none" : signal}`,
      );
      if (code === 0) {
        resolvePromise();
        return;
      }

      reject(
        new Error(
          `${command} ${args.join(" ")} exited with code ${String(code)}${signal === null ? "" : ` and signal ${signal}`}.`,
        ),
      );
    });
  });
}

async function runTimedCommand(input: {
  label: string;
  command: string;
  args: ReadonlyArray<string>;
}): Promise<void> {
  const startedAt = Date.now();
  await runCommand(input.command, input.args);
  console.info(
    `[integration] ${input.label} completed in ${formatDuration(Date.now() - startedAt)}.`,
  );
}

async function loadSharedInfraCoordinator(): Promise<SharedInfraCoordinator> {
  // The runner must build workspace packages before loading harness internals.
  return await import("../../packages/test-harness/src/services/shared-infra-coordinator.ts");
}

async function loadRunnerServicePools(): Promise<RunnerServicePools> {
  // The runner must build workspace packages before loading harness internals.
  return await import("../../packages/test-harness/src/environment/runner-service-pool.ts");
}

async function main(): Promise<void> {
  const startedAt = Date.now();
  markIntegrationTimingStart(process.env);
  const runnerPoolSession = ensureIntegrationRunnerPoolSession(process.env);
  const cliArgs = normalizeCliArgs(process.argv.slice(2));
  const projectFilters = parseProjectFilters(cliArgs);
  const fileFilters = parseIntegrationFileFilters(cliArgs);
  const selectedProjects = resolveSelectedProjects(projectFilters);
  const selectedBuildPackages = new Set<string>(RequiredBuildPackages);

  for (const project of selectedProjects) {
    selectedBuildPackages.add(project.packageName);
  }

  console.info(`Using integration run id ${runnerPoolSession.runId}.`);
  await ensureIntegrationConfigPath({
    runnerPoolSession,
    environment: process.env,
  });
  writeIntegrationTimingEvent(
    "runner selected projects",
    selectedProjects.map((project) => project.projectName).join(", "),
  );

  await runTimedCommand({
    label: "build",
    command: "pnpm",
    args: [
      "turbo",
      "run",
      "build",
      ...Array.from(selectedBuildPackages).flatMap((packageName) => [
        "--filter",
        `${packageName}...`,
      ]),
    ],
  });

  const sharedInfraCoordinator = await loadSharedInfraCoordinator();
  const runnerServicePools = await loadRunnerServicePools();

  try {
    await prewarmSharedInfra(selectedProjects, fileFilters, sharedInfraCoordinator);
    await runTimedCommand({
      label: "vitest",
      command: "pnpm",
      args: ["exec", "vitest", "run", "-c", "vitest.integration.root.ts", ...cliArgs],
    });
  } finally {
    const cleanupStartedAt = Date.now();
    await runnerServicePools.stopRunnerServicePools({
      runId: runnerPoolSession.runId,
      coordinatorDir: runnerPoolSession.coordinatorDir,
    });
    await sharedInfraCoordinator.stopSharedInfraForTestRun(runnerPoolSession.runId);
    console.info(
      `[integration] pooled service/infra cleanup completed in ${formatDuration(Date.now() - cleanupStartedAt)}.`,
    );
  }

  console.info(`[integration] total completed in ${formatDuration(Date.now() - startedAt)}.`);
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? (error.stack ?? error.message) : String(error);
  console.error(message);
  process.exitCode = 1;
});
