-- squawk-ignore-file ban-drop-not-null
ALTER TABLE "control_plane"."automation_conversation_delivery_tasks" ALTER COLUMN "source_webhook_event_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "control_plane"."automation_conversation_delivery_tasks" ADD COLUMN "source_scheduled_action_id" text;--> statement-breakpoint
ALTER TABLE "control_plane"."automation_conversation_delivery_tasks" ADD CONSTRAINT "automation_conversation_delivery_tasks_source_scheduled_action_id_scheduled_actions_id_fk" FOREIGN KEY ("source_scheduled_action_id") REFERENCES "control_plane"."scheduled_actions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "automation_conversation_delivery_tasks_source_scheduled_action_id_idx" ON "control_plane"."automation_conversation_delivery_tasks" USING btree ("source_scheduled_action_id") WHERE "control_plane"."automation_conversation_delivery_tasks"."source_scheduled_action_id" is not null;--> statement-breakpoint
CREATE INDEX "automations_organization_id_created_at_id_idx" ON "control_plane"."automations" USING btree ("organization_id","created_at","id");--> statement-breakpoint
CREATE UNIQUE INDEX "schedule_automations_automation_id_uidx" ON "control_plane"."schedule_automations" USING btree ("automation_id");--> statement-breakpoint
CREATE INDEX "scheduled_actions_pending_recovery_idx" ON "control_plane"."scheduled_actions" USING btree ("scheduled_at","id") WHERE "control_plane"."scheduled_actions"."status" = 'pending';--> statement-breakpoint
CREATE INDEX "scheduled_actions_dispatching_recovery_idx" ON "control_plane"."scheduled_actions" USING btree ("scheduled_at","dispatching_at","id") WHERE "control_plane"."scheduled_actions"."status" = 'dispatching';--> statement-breakpoint
ALTER TABLE "control_plane"."automation_conversation_delivery_tasks" ADD CONSTRAINT "automation_conversation_delivery_tasks_exactly_one_source_check" CHECK (("control_plane"."automation_conversation_delivery_tasks"."source_webhook_event_id" is not null and "control_plane"."automation_conversation_delivery_tasks"."source_scheduled_action_id" is null) or ("control_plane"."automation_conversation_delivery_tasks"."source_webhook_event_id" is null and "control_plane"."automation_conversation_delivery_tasks"."source_scheduled_action_id" is not null));
