DROP INDEX "control_plane"."automation_conversation_delivery_tasks_automation_conversation_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."automation_conversation_routes_automation_conversation_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."automation_conversations_organization_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."automation_conversations_org_owner_idx";--> statement-breakpoint
DROP INDEX "control_plane"."automation_runs_automation_target_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."automations_organization_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."int_conn_dev_auth_attempts_org_idx";--> statement-breakpoint
DROP INDEX "control_plane"."integration_connection_redirect_sessions_organization_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."integration_connections_organization_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."integration_credentials_organization_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."integration_webhook_events_integration_webhook_source_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."integration_webhook_events_target_key_idx";--> statement-breakpoint
DROP INDEX "control_plane"."members_organization_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."spv_integration_bindings_profile_id_version_idx";--> statement-breakpoint
DROP INDEX "control_plane"."scheduled_actions_schedule_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."schedules_organization_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."team_members_team_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."user_ext_principal_cred_secrets_org_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."user_ext_principal_cred_secrets_cred_id_idx";--> statement-breakpoint
DROP INDEX "control_plane"."webhook_automations_automation_id_idx";