# Typos configuration is within _typos.toml
---
name: Typos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

permissions:
  contents: read

jobs:
  typos:
    name: Check for typos
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Typos
        uses: crate-ci/typos@57b11c6b7e54c402ccd9cda953f1072ec4f78e33 # v1.43.5
