# Typos configuration is within _typos.toml
---
name: Typos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

permissions:
  contents: read

jobs:
  typos:
    name: Check for typos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Typos
        uses: crate-ci/typos@5374cbf686e897b15713110e233094e2874de7ef # v1.46.1
